### ISSUE TITLE
Cannot run terminal commands after downloading and installing tool

### ISSUE THREAD

**Issue by clfristoe** [msintuneappsdk/intune-app-wrapping-tool-ios#10]
When I run the .dmg it gets mounted separately and I get the following terminal error when trying to wrap an app. 

<img width="568" alt="screen shot 2018-08-08 at 4 11 38 pm" src="https://user-images.githubusercontent.com/15655814/43864617-c4fa9b04-9b25-11e8-9e36-3a29f83e0482.png">

**Comment by Kyle-Reis** [comment]
Hey @clfristoe, I'm guessing that you executed the above command from the /Volumes directory, and that you mounted 8.1.1 before unmounting the older version, then unmounted the older one? I just tried this myself and am getting the same error. It seems that in this case, Finder displays both the new and old volumes as "IntuneMAMPackager", but in reality, the new version has been mounted as "IntuneMAMPackager 1".

So, there are 2 ways you can fix this:

Option 1:  Unmount then remount version 8.1.1, then run the same command
Option 2: Run this command instead: /IntuneMAMPackager\ 1/Contents/MacOS/IntuneMAMPackager

**Comment by clfristoe** [comment]
@Kyle-Reis Thank you for the quick reply! This is my first time installing and using the wrapping tool, so I don't have an older version on my machine. I unmounted version 8.1.1 and searched for any occurrences of Intune. I then remounted version 8.1.1 and ran the same command. In the documentation on Microsoft's site (https://docs.microsoft.com/en-us/intune/app-wrapper-prepare-ios), it says the packager may get mounted separately and will result in "file not found" errors. Their suggestion is to move the contents of the main folder so that it can be found during wrapping. I have also tried this, but to no avail. I also ran 'which IntuneMAMPackager' and there was no result, so I am wondering if mac is having a hard time finding the packager.

**Comment by clfristoe** [comment]
@Kyle-Reis after working it a bit more, I ended up copying the files inside IntuneMAMPackager to a file named Intune on my desktop. I then navigated to the Desktop and ran the following command : 
./Intune/Contents/MacOS/IntuneMAMPackager -i ... and it worked properly.

**Comment by Kyle-Reis** [comment]
@clfristoe In the future you can just run this command instead:

/Volumes/IntuneMAMPackager/Contents/MacOS/IntuneMAMPackager 

You shouldn't need to copy the contents of the mounted volume anywhere.

I think what was happening was that you copy-pasted the exact command from that documentation, but weren't running it from the /Volumes directory. The "." at the beginning of the command you pasted means that the path you specified begins from the current working directory. It would work if you first changed directories to /Volumes - cd /Volumes

**Comment by clfristoe** [comment]
@Kyle-Reis  I see, that makes sense. I just tried that and it worked. Thank you for the help.

**Comment by Kyle-Reis** [comment]
Great to hear. I'll be submitting a change to the docs to avoid this sort of confusion for others :)

**Comment by clfristoe** [comment]
I'm sure that will be helpful to many others!
