### ISSUE TITLE
App Not Set Up when using parameters aa, ac and ar

### ISSUE THREAD

**Issue by anste** [msintuneappsdk/intune-app-wrapping-tool-ios#103]
We are trying to deploy a wrapped Apache Cordova iOS app. Until now this works as expected but Microsoft announced that an AAD app-registration becomes mandatory by end of August 2023 (MC513662 and MC547638).
So we created the App-Registration and added the parameters -aa, -ac and -ar before wrapping:

aa: https://login.microsoftonline.com/<Tenant_ID>
ac: <Client_ID>
ar: <url_scheme_of_app>

Now we get the following message:

> App Not Set Up: This app has not been set up for you to use. Contact your IT administrator for help.

To me it is unclear whether it is mandatory for the app to implement MSAL? The app uses another identity provider for authentication.
I have no access to the AAD configuration but maybe you can give hints I can forward.

**Comment by chadseippel** [comment]
Hello @anste . The error message suggests a possible configuration mismatch. Can you gather logs (they can be gathered in the wrapped apps iOS settings), and send them to chseippe@microsoft.com? Also please verify that your aa, ac and ar, values match the values in your app registration created in Azure portal.

**Comment by anste** [comment]
Hello @chadseippel thank you for your response!
What do we have to configure for "ar"? We can use a custom URL-scheme but AAD doesn't let us configure an URL other than https or localhost.

**Comment by ShruthiAchutha** [comment]
Closing stale issues. Please reopen if you still need help with this.
