### ISSUE TITLE
'Account Not Set Up' after wrapping the iOS app

### ISSUE THREAD

**Issue by yogendrajs** [msintuneappsdk/intune-app-wrapping-tool-ios#107]
**Describe the issue**
After successfully executing the commands for the app-wrapping tool for iOS, I deployed the LOB app to the Intune portal. But when the user tries to sign in to the app after installing, it says "Account Not Set Up".

The command being used is `/Volumes/IntuneMAMAppPackager/IntuneMAMPackager/Contents/MacOS/IntuneMAMPackager -i <app.ipa> -o <app_wrapped.ipa> -p <provisioning_profile> -c <sha1 hash>  -v true `

The input app was signed with an Apple distribution certificate and an ad-hoc profile using XCode.

**Prerequisites before wrapping the app**
- What platform is your app based on? React Native
- XCode and command line tools: v15.1
- Minimum iOS version chosen: v14.0
- App Wrapping tool version: v19.0.1

**Screenshot**
![IMG_4678](https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/assets/43265032/6cc7e7c9-c897-4900-8650-934c6659b22b)

**Intune App Portal**
I've deployed the "App protection policy" to the user's security group and it also targets our custom LOB iOS app.
The app does not use MSAL as the identity provider for authentication.

Please take a look into what could've possibly been missed and let me know if any additional details need to be added.

**Comment by yogendrajs** [comment]
One more question: I read in the docs and I also am not able to use the configured SSO within the app (not MSAL). If I want to use the SSO also, do I need to use the MSAL to get it working?

**Comment by abasore** [comment]
@yogendrajs we would expect to see that error if the user was not licensed for Intune. Can you confirm signed in user has na active Intune license? Here is a doc with more info: https://learn.microsoft.com/en-us/mem/intune/fundamentals/licenses-assign

**Comment by yogendrajs** [comment]
Yes, it took sometime ~12hrs to finally getting policy activated after
deploying it.

Thanks for your concern. We can close this.
