### ISSUE TITLE
wrapped ipa can't upload to IOS Appstore

### ISSUE THREAD

**Issue by Abhijith-G** [msintuneappsdk/intune-app-wrapping-tool-ios#11]
Hello ,

Can we upload wrapped ipa wrapped using intune wrapping tool in ios appstore(xamarin forms app). Is it possible to do this.

Thanks in advance

**Comment by msintuneappsdk** [comment]
Hi @Abhijith-G, we do not support Xamarin apps using the Intune app wrapping tool today. Please take a look at our Intune Xamarin Bindings: https://docs.microsoft.com/en-us/intune/app-sdk-xamarin

**Comment by yogendrajs** [comment]
@msintuneappsdk @Kyle-Reis - Intune SDK-enabled apps also prompt for credentials when they're coded with `MAMPolicyRequired` to receive an App protection policy.

Any specific reason for not recommending wrapped apps to upload to the App Store? (couldn't find it in the docs)

**Comment by yogendrajs** [comment]
@Kyle-Reis but that will also be the case with SDK integration right, when the MAMPolicyRequired is set to true and the app opens up with asking for the credentials

**Comment by Kyle-Reis** [comment]
@yogendrajs - Yes, but typically MAMPolicyRequired + AutoEnrollOnLaunch are also used in custom LOB apps where the admin wants to require all users to be Intune licensed + targeted with policy.

**Comment by yogendrajs** [comment]
Yes, so just wanted to understand here if I integrate the SDK with these configurations, will it not be a problem in the App Store review just like it becomes with the wrapped app (assuming we don't provide credentials for the review process).
Can you please help me understand how it will be different from the wrapped app in this case?

**Comment by Kyle-Reis** [comment]
@yogendrajs - I can't say for certain whether Apple will approve or deny the submission if the app is wrapped or configured MAMPolicyRequired + AutoEnrollOnLaunch enabled. There is no functional difference at launch time in these two scenarios. The app will prompt for credentials on launch and will not allow a user access without an account that is Intune licensed and targeted with policy. So my recommendation would be to NOT use either approach if you intend to upload to the app store without providing any test credentials for the app that have an Intune license assigned + policy targeted.
