### ISSUE TITLE
"Unsupported Xcode Version" when trying to wrap an app compiled with Xcode 15.2

### ISSUE THREAD

**Issue by AntoineRuf69** [msintuneappsdk/intune-app-wrapping-tool-ios#110]
**Describe the bug:**
Trying to wrap an application compiled with Xcode 15.2 doesn't work.

**To Reproduce**
1. Compile a new version of the application using the latest release of Xcode (15.2 stable)
2. Launch Intune Wrapping Tool for iOS (latest version) with a supplied plist file containing all parameters (using a new distribution provisioning profile only for our app with Intune, and a certificate we used to publish a new version of the application last week.-
3. An error "unsupported Xcode version" is encountered.

**Expected behavior:**
A wrapped IPA that I can use and distribute via the Intune Admin centre
**Screenshots and logs:**
Here's the full log of the command (with names and app IDs redacted) : 
`/Volumes/IntuneMAMAppPackager/IntuneMAMPackager/Contents/MacOS/IntuneMAMPackager -f PackagerArgumentExample.plist
Warning: You must specify an AAD client identifier.
Warning: You must specify an AAD reply URI.
Application packaging in progress...
Version of MACOSX is 13.5.2
Version of XCode installed is Xcode 15.2
Build version 15C500b

Parsing provisioning profile...
Parsing main app provisioning profile...
Parsing extension provisioning profiles...
Checking that main provisioning profile has not expired...
Checking that extension provisioning profiles have not expired...
Checking if signing certificate is valid...
Provided certificate name length matches that of SHA1 hash.
Number of certificates returned by query: 3
Checking certificate at index: 0
Getting certificate common name.
Computing SHA-1 fingerprint of current certificate.
Computing SHA-1 fingerprint of provided certificate.
Checking certificate at index: 1
Getting certificate common name.
Computing SHA-1 fingerprint of current certificate.
Computing SHA-1 fingerprint of provided certificate.
Checking certificate at index: 2
Getting certificate common name.
Computing SHA-1 fingerprint of current certificate.
Computing SHA-1 fingerprint of provided certificate.
Possible fingerprint match found. Checking if certificate is contained in provisioning profile...
Computing SHA-256 fingerprint of certificate.
Checking if SHA-256 hash exists in provisioning profile.
Certificate was found in the provisioning profile.
Checking if certificate issuer is Apple.
Checking if signing certificate is found in each extension profile...
Creating temporary directories...
Input Parameters
 Path to input application:		/Users/REDACTED/Desktop/REDACTED-developer.ipa
 Path to output application:	/Users/REDACTED/Desktop/wrapped-REDACTED.ipa
 Provisioning profile:			/Users/REDACTED/Desktop/REDACTED_Intune.mobileprovision
 Certificate:		5E 81 34 AC D5 55 1E 1B 39 31 CD 6C EB F3 17 14 A6 54 9F E3
WARNING: This application supports opening one or more file types, but does not have the appropriate entitlements to be supported with Intune APP. An additional provisioning profile needs to be specified using the -x command line argument. This profile must have a wildcard application-identifier or must have an application-identifier of 'com.REDACTED.REDACTED.standard.IntuneOpenInAction.IntuneOpenInAction' and must contain at least one application group which is shared with the main application. If this profile is not specified, other Intune APP enabled applications will not be able to send files to this application.
Packager Version: 18.0.0, Packager Build: 20230912.3, App Build: 3.0.999, Concatenated Build: 20230933.3.999
The input app was built with an unsupported xcode version.`

**Smartphone (please complete the following information):**
- OS : targeting the last version of iOS, iOS 17.

**Intune app wrapping tool (please complete the following information):**
We're trying to wrap an app of ours to be used with restricted permissions in the client's environment.

Any help is appreciated, as we're kinda stuck right now without the wrapping tool working.

**Comment by msft-neiljac** [comment]
Hi @AntoineRuf69.

What is the DTXcode value in your compiled application's Info.plist?

Thanks,
Neil

**Comment by AntoineRuf69** [comment]
Hi @msft-neiljac ,

DTXCode is 0500, DTXCodebuild is 5A1413.
We don't use an Xcode project, so I suspect the plist file is fixed and didn't include the "true" Xcode version used to generate the app.
I'll try again with a modified plist file and keep you posted.
Regards,
Antoine.

**Comment by AntoineRuf69** [comment]
Trying with a modified plist file with updated version and build, the wrapping process goes a bit further.
Thank you for your help.

Regards,
Antoine.
