### ISSUE TITLE
AADSTS650057: Invalid resource. The client has requested access to a resource which is not listed in the requested permissions in the client's application registration.

### ISSUE THREAD

**Issue by sabaricod** [msintuneappsdk/intune-app-wrapping-tool-ios#111]
**Describe the bug:**
App is wrapped successfully but there was this error popping up after all the login details is entered and next is clicked

**To Reproduce**
I have wrapped an app with command parameters -aa,-ar and -ac as given. no extra config have been done in microsoft entra. 

this is how the command i have used looks like

Volumes/IntuneMAMAppPackager/IntuneMAMPackager/Contents/MacOS/IntuneMAMPackager -i  /Users/sabari/MOBILETEST/MOBILE.ipa -o /Users/sabari/TEST/TEST.ipa  -p /Users/sabari/Downloads/test.mobileprovision -c "SHA1-KEY" -aa https://login.microsoftonline.com/[tenant-id] -ac [client-id] -ar msal8b6db35c-bc49-4a15-9633-f**************://auth -v true. I have attached a screenshot below.  Please let me know if i am doing anything wrong in terms of -ar parameter. 

![Image](https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/assets/94745152/3300b35b-028e-484e-9d2f-a5843dce347a)

**Expected behavior:**
after entering credentials it is supposed to route back to application with successful login

**Screenshots and logs:**
- If applicable, add screenshots to help explain your problem. 
- If your app is crashing post-wrapping, do you have app logs for the crash itself? 
- If your app is crashing pre-wrapping, do you have app logs for the wrapper errors? 

**Smartphone (please complete the following information):**
 not device related , happens in all devices

**Intune app wrapping tool (please complete the following information):**
- What version of the wrapper are you using? Are you using the latest version - latest version
- What platform is your app based in (Java, Xamarin based, Cordova, etc) - react native
- For pre-wrapping errors, does the app build without being wrapped - no pre wrapping errors, yes it works
- For post-wrapping errors, does the app launch without being wrapped - yes app launches and i was able to enter my credentials and then it stops with AADSTS650057 error.

THIS IS URGENT AS WE ARE NEARING THE PRODUCTION DATE !! please guide us

**Comment by wangxiaoms** [comment]
Hi, please follow the third step here:
https://learn.microsoft.com/en-us/mem/intune/developer/app-wrapper-prepare-ios#register-your-app-with-microsoft-entra-id
_3. Give your app access to the Intune MAM service. For more information, see [Give your app access to the Intune Mobile App Management service](https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-get-started#give-your-app-access-to-the-intune-mobile-app-management-service)._

**Comment by sabaricod** [comment]
Given that permission enabled, app just popped out and was not able to log in and app get crashed. this is the error i get now.

An OAuth redirect was sent to a OIDExternalUserAgentSession after it already completed.

we usually have azure authentication after azure authentication gets completed we immediately will call oneconnect api.

Is this what that causes the app to crash? @wangxiaoms

**Comment by wangxiaoms** [comment]
@sabaricod Since original permission problem is solved, I will close this issue, you may open new issue for other problem if needed.

**Comment by sabaricod** [comment]
An OAuth redirect was sent to a OIDExternalUserAgentSession after it already completed.
