### ISSUE TITLE
Getting NotEnoughProvisioingProfiles but no docs explaining this error

### ISSUE THREAD

**Issue by deeyodc-symphony** [msintuneappsdk/intune-app-wrapping-tool-ios#12]
I am currently trying to wrap an ipa with the InTune wrapping tool. However, I am getting an error that I can not seem to find any help or documentation on.

I have created signing certificate and provisioning profile but am always getting an error.

**Comment by Kyle-Reis** [comment]
Hey @deeyodc-symphony, the wrapper should be outputting a more detailed message, but due to a bug you've uncovered, it is not. I'm working on the fix for that. The error message this token maps to is "There are more extensions than specified provisioning profiles. Each extension must have a corresponding provisioning profile, or a wildcard profile must be specified."

**Comment by vishnugnair** [comment]
Hi @deeyodc-symphony were you able to fix the issue? I am facing the exact same problem now.

**Comment by muringmachine** [comment]
Hi @Kyle-Reis - If we get the "There are more extensions than specified provisioning profiles. Each extension must have a corresponding provisioning profile, or a wildcard profile must be specified." how do we fix this issue? We are facing this issue now. Thanks!

**Comment by Kyle-Reis** [comment]
@muringmachine it sounds like the app you are attempting to wrap contains more extensions than the number of provisioning profiles you’ve specified. You’ll need to specify a provisioning profile for each extension.

**Comment by muringmachine** [comment]
@Kyle-Reis Thanks for your response. We have 2 provisioning profiles, one for the app and another one for the extension. How do we specify in the IntuneMAMPackager these 2 profiles? Currently this is the command we used which returns the error:
`IntuneMAMPackager -i mobileApp.ipa -o mobileApp_wrapped.ipa -p mobileApp_Distribution.mobileprovision  mobileApp_Shareextension.mobileprovision -c <CERTIFICATE-SHA1> -v true `

**Comment by muringmachine** [comment]
@Kyle-Reis a gentle follow up on the inquiry above. We found no documentation on how to pass 2 provisioning profile (one for each extension) when running the Intune MAM Packager command.

**Comment by Kyle-Reis** [comment]
Hey @muringmachine, you'll need to use the "-x" option to specify an array of extension provisioning profiles. In your case, it sounds like there would only be a single provisioning profile in the list. If you run the wrapper without specifying any arguments, it will output a list of all the arguments that are available to you and some examples of how to use them. Here is the example shown which includes usage of the "-x" option:

./IntuneMAMPackager/Contents/MacOS/IntuneMAMPackager -i /Users/myadmin/Documents/MyExtensionApp.ipa -o /Users/myadmin/Documents/MyExtensionApp_Wrapped.ipa -p /Users/myadmin/Documents/My_Provisioning_Profile_.mobileprovision -c "12 A3 BC 45 D6 7E F8 90 1A 2B 3C DE F4 AB C5 D6 E7 89 0F AB" -x \<array\>\<string\>/Users/myadmin/Documents/My_Share_Extension.mobileprovision\</string\>\<string\>/Users/myadmin/Documents/My_Document_Provider_Extension.mobileprovision\</string\>\</array\>

**Comment by Kyle-Reis** [comment]
Hey @muringmachine, just want to verify that you were able to successfully wrap before closing this issue. The current version of the app wrapper should now output the full error message when extension profiles are missing.

**Comment by muringmachine** [comment]
thank you, it worked!

**Comment by varunmehtaxebia** [comment]
Hello @Kyle-Reis ,

I'm still getting same error 

_`"There are more extensions than specified provisioning profiles. Each extension must have a corresponding provisioning profile, or a wildcard profile must be specified."`_

**Using below:**
`declare -a extension=(Desktop/Extension1.mobileprovision Desktop/Extension2.mobileprovision Desktop/Extension3.mobileprovision);
`
/Volumes/IntuneMAMPackager/Contents/MacOS/IntuneMAMPackager -i Desktop/my_build.ipa -o Desktop/my_intunes_wrappped.ipa -p Desktop/MainApp.mobileprovision -x ${extension[*]} -c "EE 21 34 24 65 87 9A 65 SD 74 D2 B1 78 20 0E B2 09 3B AF 37" -v true

Anything more that i need to do?
