### ISSUE TITLE
Intune MAM Wrapper returns Illegal instruction: 4  

### ISSUE THREAD

**Issue by muringmachine** [msintuneappsdk/intune-app-wrapping-tool-ios#14]
When trying to run the MAM Packager, the command returns error
line 4:   779 Illegal instruction: 4  intune/Contents/MacOS/IntuneMAMPackager 

Version of MACOSX is 10.13.6
Version of XCode installed is Xcode 9.4.1
Build version 9F2000

Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
x86_64, i386

Is it possible to create a package that is compatible with the above architecture?

**Comment by Kyle-Reis** [comment]
Hey @muringmachine, could you share the exact command you are running (don't include actual cert hash) along with full console output? Thanks.

**Comment by muringmachine** [comment]
Hi @Kyle-Reis 

This is the command we used to run the mam packager.
`intune/Contents/MacOS/IntuneMAMPackager -i MaskedApp.ipa -o MaskedApp-wrapped.ipa -p MaskedApp.mobileprovision -c notactualcerthash -v true`

This command works if we use our mac local machine with Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz 

We tried this command in the Hosted MacOS Agent Pool in VSTS as we are setting up continuous integration in our mobile builds. But using this machine returns the following error:

2018-11-23T12:27:24.9076370Z /Users/vsts/agent/2.141.1/work/_temp/1292bab2-d031-4ab8-bfa3-2a62fa97e6f4.sh: line 4:   779 Illegal instruction: 4  intune/Contents/MacOS/IntuneMAMPackager -i MaskedApp.ipa -o MaskedApp-wrapped.ipa -p MaskedApp.mobileprovision -c notactualcerthash -v true
2018-11-23T12:27:24.9221900Z ##[error]Bash exited with code '132'.

**Comment by Kyle-Reis** [comment]
Hey @muringmachine, is the OS version of the local machine the same as the hosted Mac?

**Comment by muringmachine** [comment]
hi @Kyle-Reis, yes they are the same, the Version of MACOSX is 10.13.6.

**Comment by muringmachine** [comment]
Hey @Kyle-Reis - sorry for the follow up, but is their any possible resolution for this issue?

**Comment by Kyle-Reis** [comment]
Hey @muringmachine, I tried running the wrapper in the exact environment you described:

 - Mac Pro "Six Core" 3.5 (Late 2013) - this is the only model which has the processor you described.
- MacOS version 10.13.6
- Xcode version 9.4.1

I was unable to reproduce this error. Are you using the [latest release](https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/releases/tag/9.0.3) of the wrapper?

**Comment by muringmachine** [comment]
Hello @Kyle-Reis - Thanks for providing the latest release link. I used that package to run the MAM command but same issue occurs. Attaching here a screenshot of the output, hope this can help.



![screenshot](https://user-images.githubusercontent.com/45289280/49734495-72379b00-fcbf-11e8-80c3-d7836f91c55b.JPG)

**Comment by muringmachine** [comment]
Closing issue as this was solved when we added the install certificate & profile task in the pipeline.
