### ISSUE TITLE
Support the option to optionally resign

### ISSUE THREAD

**Issue by rodfmarin** [msintuneappsdk/intune-app-wrapping-tool-ios#15]
Is it possible to support a scenario where the end user may not want to resign _inline_ with this utility?  possibly in some other step later on?

**Comment by Kyle-Reis** [comment]
Hey @rodfmarin, could you explain your scenario in a little more detail? Why don’t you want to sign during wrapping? Does signing twice have any significant impact? We haven’t received any similar requests from other customers as far as I know,so  I don’t think this is something we would prioritize unless there’s a legitimate blocking issue.

**Comment by Kyle-Reis** [comment]
Hey @rodfmarin, just checking in again to understand your scenario a bit more. If this is no longer a blocking issue for you, feel free to close out the issue.

**Comment by rodfmarin** [comment]
Hi @Kyle-Reis 
Apologies for the delayed response, and not providing sufficient details/scenarios.

As a hypothetical scenario, if I was working on a smaller team using developer certificates but wanted to publish my app to the Intune portal, I would want to sign with the distribution certificate.  Though my team may not have access to that, and it may be handled by another team at a later time.  

I think the course of action here might be to sign with the developer certificate through the wrapping utility and resign the application after with the distribution certificate; that is, if it doesn't impact the functioning of the MAM wrapping?

Could you confirm?

**Comment by Kyle-Reis** [comment]
Hey @rodfmarin, resigning the app shouldn't impact its functionality.
