### ISSUE TITLE
SegmentationFault:11

### ISSUE THREAD

**Issue by smarten-spaces** [msintuneappsdk/intune-app-wrapping-tool-ios#16]
Hi,

I am trying to run the IntuneMAMPackager but i get segmentationfault:11 everytime, and there is nothing getting printed on the logs.

here is the command i am using:
**_/Volumes/IntuneMAMPackager/Contents/MacOS/IntuneMAMPackager -i ~/Desktop/MyApp/MyApp.ipa -o ~/Desktop/MyIntuneApp.ipa -p ~/Desktop/MyApp/MyApp.mobileprovision -c “SHA-1 key here” -v true_**

what am i doing wrong here?

**Comment by Kyle-Reis** [comment]
Hey @smarten-spaces, which version of the packager are you using? We've seen a similar issue in the past, where the problem turned out to be that the signing certificate was revoked. Could you verify that you are using a valid SHA-1 hash for a valid signing cert?

**Comment by iOSUserMe** [comment]
Hi @smarten-spaces , I have faced same issue and able to resolve by modifying double quotes format.
It is just syntax error what I was facing, Hope the same issue for you.

/Volumes/IntuneMAMPackager/Contents/MacOS/IntuneMAMPackager -i ~/Desktop/MyApp/MyApp.ipa -o ~/Desktop/MyIntuneApp.ipa -p ~/Desktop/MyApp/MyApp.mobileprovision -c **“SHA-1 key here”** -v true
to
/Volumes/IntuneMAMPackager/Contents/MacOS/IntuneMAMPackager -i ~/Desktop/MyApp/MyApp.ipa -o ~/Desktop/MyIntuneApp.ipa -p ~/Desktop/MyApp/MyApp.mobileprovision -c **"SHA-1 key here"** -v true

**Comment by Kyle-Reis** [comment]
Thanks for pointing out the issue here @iOSUserMe!
