### ISSUE TITLE
Failed to inject IntuneMAM.framework into the app

### ISSUE THREAD

**Issue by shacharudi** [msintuneappsdk/intune-app-wrapping-tool-ios#17]
Hi,

I'm trying to wrap my iOS app but getting this error:
```
Failed to inject IntuneMAM.framework into the app
Cause of the error to be provided for investigation:Error Domain=Insufficient space to insert library dependency. Code=-1 "(null)"
```

Not sure if it's related but before the command fails I'm getting this warning:
```
Warning: Unable to verify system settings for certificate revocation checks
```

This is the command I'm using:
```
/Volumes/IntuneMAMPackager/Contents/MacOS/IntuneMAMPackager   -i "APP_INPUT.ipa" -o "OUTPUT_APP_PATH.ipa" -p "PROVISIONING_FILE_PATH" -c "CERT_HASH" -v true
```

I couldn't find anything about it online.. any idea's what could be the issue?

Thank you!

**Comment by shacharudi** [comment]
I managed to solve this by disabling `enable bitcode` under the target `Build Settings`

**Comment by Kyle-Reis** [comment]
Makes sense, we do not support bitcode-enabled apps.
