### ISSUE TITLE
Is it possible to automate app wrapping using Azure DevOps?

### ISSUE THREAD

**Issue by quantumarun** [msintuneappsdk/intune-app-wrapping-tool-ios#18]
We are working on integrating Intune MAM for our mobile applications to deploy apps without enrolment. Our apps are already live and were developed long back. To avoid integrating SDK we are evaluating wrapping tool.

Do we have support to integrate Intune wrapping tool to CI/CD system. Do we already have a task in Azure DevOps/Pipeline to automate this or can team provide any plugin/script to automate this?

**Comment by msintuneappsdk** [comment]
Hi @quantumarun, unfortunately there is no task today in Azure DevOps/Pipeline to automate Intune app wrapping today. If this is something you think should be added to the product, please provide your idea using [UserVoice](https://microsoftintune.uservoice.com/forums/291681-ideas?category_id=148986).

There are some customers who have investigated it themselves and successfully been able to wrap apps as a part of their build environment (i.e using Jenkins). There are no plans for us to provide such a script at this time.
