### ISSUE TITLE
IOS app with Siri intent extensions - Error message: A specified extension provisioning profile was not valid.

### ISSUE THREAD

**Issue by MirzaBasic** [msintuneappsdk/intune-app-wrapping-tool-ios#20]
I have two extensions in my app for Siri intents and Siri IntentsUI
 Al my provision profiles are valid and my app is signed correctly

 I got this error message when trying to wrap app:
"A specified extension provisioning profile was not valid."

I'm using this command for wrapping ios app:

/Volumes/IntuneMAMPackager/Contents/MacOS/IntuneMAMPackager -i ~/Desktop/MaApp.ipa -o ~/Desktop/MyAppWrapped.ipa -p ~/Desktop/inHouse.mobileprovision -c @ "27 C1 D6 E1 62 1F 12 9E 73 00 F2 B1 7A 10 2C 69 8D 46 48 23" -x \<array\>\<string\>~/Desktop/inHouse_Intents.mobileprovision\</string\>\<string\>~/Desktop/inHouse_IntentsUI.mobileprovision\</string\>\</array\>

**Comment by MirzaBasic** [comment]
I have two extensions in my app for Siri intents and Siri IntentsUI
 Al my provision profiles are valid and my app is signed correctly

 I got this error message when trying to wrap app:
"A specified extension provisioning profile was not valid."

I'm using this command for wrapping ios app:

/Volumes/IntuneMAMPackager/Contents/MacOS/IntuneMAMPackager -i ~/Desktop/MaApp.ipa -o ~/Desktop/MyAppWrapped.ipa -p ~/Desktop/inHouse.mobileprovision -c @ "27 C1 D6 E1 62 1F 12 9E 73 00 F2 B1 7A 10 2C 69 8D 46 48 23" -x \<array\>\<string\>~/Desktop/inHouse_Intents.mobileprovision\</string\>\<string\>~/Desktop/inHouse_IntentsUI.mobileprovision\</string\>\</array\>

**Comment by Kyle-Reis** [comment]
Hey @MirzaBasic, you should remove the '@' before your cert hash. It also looks like you're missing a '~' at the beginning of the paths to you app's provisioning profile as well as the extension provisioning profiles.
