### ISSUE TITLE
Intune app wrapping tool for iOS support for Swift apps built with Xcode 10.2+

### ISSUE THREAD

**Issue by msintuneappsdk** [msintuneappsdk/intune-app-wrapping-tool-ios#21]
The Intune app wrapping tool for iOS does not yet support Swift apps built with Xcode 10.2+. These apps use Swift libraries that are baked into the OS on iOS 12.2+. 

Obj-C apps or any app built on an older version of Xcode should continue to use the framework that is currently available.

The development team is working to release a new framework for Swift apps built with Xcode 10.2+.

**Comment by thebugcode** [comment]
Hi Development team. We are failing to wrap the app using the wrapping tool . Apple sent en email informing us the build is invalid: "We identified one or more issues with a recent delivery for your app, "Banky App". Please correct the following issues, then upload again. Invalid Swift Support - The SwiftSupport folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit it."

I can see that the input .ipa contains a Payload & SwiftSupport folder at the root level, whereas the wrapped.ipa file produced by the wrapping tool, skips the SwiftSupport folder. When can we expect this to be resolved?

**Comment by Kyle-Reis** [comment]
Hey @thebugcode, which version of Xcode are you building your app with?

**Comment by Kyle-Reis** [comment]
FYI, @thebugcode, we're tracking your your issue in #26 and closing this one, as it refers to some hooks we needed to add to support Swift apps built with Xcode 10.2+
