### ISSUE TITLE
Intune Wrapping changes the Bundle Version

### ISSUE THREAD

**Issue by quantumarun** [msintuneappsdk/intune-app-wrapping-tool-ios#23]
I am Intune Wrapping tool to wrap and upload the app to Intune Portal.
Before the wrapping Application Version is: 4.1(3.2) 

After Wrapping Application Version is changed to: 4.1(180930.3.3)

It seems Bundle Version is getting changed after wrapping.
Why do Bundle Version changed after wrapping? I need the same version as the original IPA.

**Comment by raionesc** [comment]
Hi @quantumarun, have you tried to append -b to your command for wrapping the app?
Details here about the parameter - https://docs.microsoft.com/en-us/intune/app-wrapper-prepare-ios#command-line-parameters

**Comment by Kyle-Reis** [comment]
Hey @quantumarun by default the app wrapping tool does update the bundle version. To be clear the bundle version field is actually meant to represent a specific build of a given version of the app. The "Bundle versions string, short" field represents the actual version of the app. This is called out in [Apple's documentation](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html) on these two fields. The reason we change the build number by default is to support the scenario of wrapping the same version of an app with a newer version of the Intune SDK, and deploying it as an update via Intune (or another MDM provider). If the version/build numbers of the previous app and new app are exactly the same, you won't be able to successfully update the app on end-user's devices as Intune would have no way of determining that the version of the app on the end user's device differs from what has been uploaded to the Intune service. This is the reasoning for the build number update. If you do decide to use the "-b" option, please keep this caveat in mind when updating to a newer version of Intune: your app's build or version number must also be updated.

**Comment by Kyle-Reis** [comment]
Alternatively, you could also deploy the same app version/newer Intune SDK by deleting the old instance of the app in the Intune portal, and uploading it as a new app.
