### ISSUE TITLE
Will an app wrapped with inTune wrapping tool pass apple review?

### ISSUE THREAD

**Issue by thebugcode** [msintuneappsdk/intune-app-wrapping-tool-ios#24]
I'd like to distribute an inTune wrapped app not on the public AppStore but on the Private AppStore(VPP, Bussiness to Business app distribution).
I am wondering if there are any chances of such an app passing Apple review.

**Comment by Kyle-Reis** [comment]
Hey @thebugcode, the app wrapping tool is meant for LOB apps that are distributed by an organization internally, where the customer may not have direct source code access or the technical ability to integrate our SDK. It was not developed for the purposes of submission to Apple's app store or passing any Apple review process, so this scenario is [technically unsupported](https://docs.microsoft.com/intune/apps-prepare-mobile-application-management#intune-app-wrapping-tool). If you have source code access, the recommendation is to [integrate the Intune App SDK ](https://docs.microsoft.com/intune/app-sdk-ios) if you plan on submitting to any app store and passing Apple review.
