### ISSUE TITLE
SwiftSupport folder missing from wrapped application

### ISSUE THREAD

**Issue by Kyle-Reis** [msintuneappsdk/intune-app-wrapping-tool-ios#26]
Hi Development team. The wrapping tool creates an invalid IPA file . Apple sent en email informing us the build is invalid: "We identified one or more issues with a recent delivery for your app, "Banky App". Please correct the following issues, then upload again. Invalid Swift Support - The SwiftSupport folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit it."

We can see that the input .ipa contains a Payload & SwiftSupport folder at the root level, whereas the wrapped.ipa file produced by the wrapping tool, doesnt embed the SwiftSupport folder. When can we expect this to be resolved?

_Originally posted by @thebugcode in https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/issues/21#issuecomment-493940005_

**Comment by Kyle-Reis** [comment]
@thebugcode, could you please let me know the Xcode version, and Swift version used to build your app? I'm trying to understand the conditions that cause the SwiftSupport directory to appear as I have not been able to generate a .ipa file that contains one

**Comment by Kyle-Reis** [comment]
@thebugcode, checking in again to see if you're still blocked by this.

**Comment by Kyle-Reis** [comment]
Closing out this issue due to inactivity. If you're still experiencing this issue and would like some help, feel free to reopen!

**Comment by jacobwarduk** [comment]
Can we get this issue re-opened? Our team is currently blocked by this.

**Comment by Kyle-Reis** [comment]
Hey @jacobwarduk, which version of Xcode was used to compile the app?

**Comment by leohenriq** [comment]
did you or @msintuneappsdk have any updates for a solution of this issue? because the link ([#21](https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/issues/21)) has already been a year....

**Comment by Kyle-Reis** [comment]
Hi @leohenriq, which version of Xcode was the app compiled with?

**Comment by leohenriq** [comment]
@Kyle-Reis Xcode version:11.3... 
I understand that in the link from microsoft this is saying that it works until version 10.2, but a year ago this post from them and that's exactly what I want to know if there was no update to accept versions higher than 10.2

**Comment by Kyle-Reis** [comment]
Hi @leohenriq, Xcode versions higher than 10.2 are now supported. In fact the minimum required Xcode version is now Xcode 11. Are you seeing the same problem mentioned in this issue with SwiftSupport folder? If so, what is the minimum supported iOS version of your application?

**Comment by leohenriq** [comment]
Hello @Kyle-Reis, the minimum supported iOS version is 9

**Comment by Kyle-Reis** [comment]
Hi @leohenriq, with version 14.0.0 of the app wrapper, the minimum supported iOS version is iOS 13. Does Xcode still produce this SwiftSupport directory when the app is compiled for a target OS of iOS 13?

**Comment by leohenriq** [comment]
Hello @Kyle-Reis, yes, this folder is there when it passes through Xcode, it disappears when it passes through the wrapping tool

**Comment by leohenriq** [comment]
Hi @Kyle-Reis , have any ideias for my problem?

**Comment by Kyle-Reis** [comment]
Hi @leohenriq, before building with Xcode, did you change the deployment target to iOS 13.0 under "Deployment Info" target settings?

![image](https://user-images.githubusercontent.com/7443106/101368108-c22ca680-3874-11eb-9b5a-12d9d59a3958.png)

**Comment by leohenriq** [comment]
Hello @Kyle-Reis, Yes, i did... but the same thing happens.

**Comment by jacobwarduk** [comment]
> Hey @jacobwarduk, which version of Xcode was used to compile the app?

We are using Xcode 12.2

**Comment by jacobwarduk** [comment]
For anybody else landing here with the same issue, we are using this workaround to add the Swift Support folder into the IPA successfully: https://stackoverflow.com/a/62457388

**Comment by NityaSantosh26** [comment]
For anyone having this issue, can use this
Follow the instructions and app will be accepted by Apple.
https://github.com/NityaSantosh26/add-swift-support

**Comment by ShruthiAchutha** [comment]
Closing stale issues. Please reopen if you still need help with this.
