### ISSUE TITLE
Push notifications don't work after wrapping

### ISSUE THREAD

**Issue by georgechr** [msintuneappsdk/intune-app-wrapping-tool-ios#27]
**Describe the bug:**
When built in release mode the app receives push notifications just fine. If we wrap the exact same app using the wrapping tool  then it doesn't receive them any more.

**To Reproduce**
1. Wrap iOS app as described in the MSDN page
2. Use the same prod distribution profile as the one used for the vanilla app

**Expected behavior:**
Push notifications work

**Actual behavior:**
Push notifications don't work

**Smartphone (please complete the following information):**
 - Any iOS device

**Intune app wrapping tool (please complete the following information):**
- What version of the wrapper are you using? Are you using the latest version?
11.0.3
- What platform is your app based in (Java, Xamarin based, Cordova, etc)?
Swift

**Comment by Kyle-Reis** [comment]
Hey @georgechr, could you try out the [latest release](https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/releases/latest) (version 11.0.8)? If the issue persists, could you share the exact command line arguments you are specifying when wrapping? You don't need to share the actual signing cert hash

**Comment by Kyle-Reis** [comment]
Hey @georgechr, are you still seeing the issue?

**Comment by georgechr** [comment]
Hey, no, not any more. Fixed after cleaning everything and starting from scratch. I am not sure which step went wrong the first time

**Comment by Kyle-Reis** [comment]
OK. Thanks for verifying!

**Comment by charlesionlake** [comment]
Can you go into more detail about what was done here to fix this? I am currently facing the same issue @georgechr
