### ISSUE TITLE
How to deal with multiple certificates with the same name?

### ISSUE THREAD

**Issue by rliljest** [msintuneappsdk/intune-app-wrapping-tool-ios#29]
Looking at the release notes for `11.2.0`, specifying a cert hash is deprecated and the name of the cert should be used instead. We have a mix of wrapped and public apps, and have two distribution certificates with the same name (one for internally distributed applications and one for publicly distributed applications).

What steps should we use to disambiguate between the two when wrapping if they have identical names?

**Comment by Kyle-Reis** [comment]
Hey @rliljest, is the same provisioning profile used to sign with both certs? The tool should select the right cert based on what certs are listed in the profile.

**Comment by rliljest** [comment]
You are absolutely right, thanks!
