### ISSUE TITLE
Unable to launch the IntuneMAMPackager on MacOS 10.15

### ISSUE THREAD

**Issue by ram2386** [msintuneappsdk/intune-app-wrapping-tool-ios#32]
@Kyle-Reis: I am getting the same error message in the IntuneMAMPackager in Terminal with MacOS 10.15 while installing the latest source file.

Please find the attached screenshot for your reference.

<img width="1151" alt="Screenshot 2019-11-05 at 3 45 18 PM" src="https://user-images.githubusercontent.com/217577/68199397-fbe10d00-ffe3-11e9-8f3d-f8a01f093b80.png">

**Comment by Kyle-Reis** [comment]
Hey @ram2386 this is a different message from the one previously reported. I saw it as well after my upgrade to 10.15.

Here's what you can do to fix it:
1.) System preferences -> Security and Privacy -> General -> Allow apps downloaded from:
   - Ensure that "App store and identified developers" is selected

2.) Right click on the IntuneMAMPackager executable
3.) Select open
4.) Verify that you want to run the executable

After this you should be able to run from terminal, even after unmounting/remounting and even after downloading a new copy of the DMG and mounting that.

**Comment by ram2386** [comment]
Thanks, it is working.
