### ISSUE TITLE
Not able to wrap ios app with an extension, how to provide the array of provisioning profiles with the -x option? I tried  <array><string>path_to_provisioning_profile_file</string></array>  and its giving error,  syntax error near unexpected token `<'

### ISSUE THREAD

**Issue by arusselkm** [msintuneappsdk/intune-app-wrapping-tool-ios#34]
**Describe the bug:**

**To Reproduce**

**Expected behavior:**

**Screenshots and logs:**
- If applicable, add screenshots to help explain your problem. 
- If your app is crashing post-wrapping, do you have app logs for the crash itself? 
- If your app is crashing pre-wrapping, do you have app logs for the wrapper errors? 

**Smartphone (please complete the following information):**

**Intune app wrapping tool (please complete the following information):**
- What version of the wrapper are you using? Are you using the latest version?
- What platform is your app based in (Java, Xamarin based, Cordova, etc)?
- For pre-wrapping errors, does the app build without being wrapped?
- For post-wrapping errors, does the app launch without being wrapped?
- Who is the customer?
- Do you see a trend with it only being reproduced on a specific device?

**Additional context:**

**Comment by Kyle-Reis** [comment]
Hey @arusselkm, you need to escape the '<' and '>' characters with a backslash ('\'). Alternatively, you could specify all of your arguments, including the list of extension provisioning profiles, in a plist files, and provide that plist file to the app wrapping tool using the -f option. Please see PackagerArgumentExample.plist in the root of the repository.
