### ISSUE TITLE
App Store rejects to accept wrapped binary. ERROR ITMS-90668: "Invalid Bundle Executable.

### ISSUE THREAD

**Issue by jupasources** [msintuneappsdk/intune-app-wrapping-tool-ios#37]
Hello,

App Store rejects to accept wrapped binary with following error:
`**ERROR ITMS-90668**: "Invalid Bundle Executable. The executable file 'Zalaris HR.app/Frameworks/ADAL.framework/ADAL' contains incomplete bitcode. To compile binaries with complete bitcode, open Xcode and choose Archive in the Product menu."`

This is Cordova based app that is built using **phonegap** service. The service is using Xcode 10.1 to build the app. Wrapping process finishes without any errors, but during upload to App Sore using new **Transporter** app it returns the error mentioned above.

I have tried to install locally both the latest Xcode 11.3.1 and also old 10.3 - same results. The wrapping is successful but upload is not. 

I noticed that with wrapping tool version 11.0.8 it works fine and App Store accepts the binary. But starting from version 11.2.0 all (including latest one) App Store rejects the binary with the error mentioned above.

I know that wrapped apps are not supposed to be published, but we have a business requirement to have it published since the app is intended for many of our customers.

Thank you!

**Comment by gastaffo** [comment]
As of now the Intune iOS MAM SDK does not support bitcode, so a wrapped app will not be able to support bitcode. Do you have the original project for the app or just the ipa?

**Comment by jupasources** [comment]
OK. I have the original project generated by Cordova CLI tool. I tried to build with bitcode enabled and also with bitcode disabled, but still same error returned by Apple ITMS. Interesting: if I wrap with wrapping tool version 11.0.8 no errors returned by Apple ITMS.

**Comment by gastaffo** [comment]
So the a difference that seems pertinent is that 11.0.8 uses ADAL 2.6.3 while 11.2.0(and later) use ADAL 4.0.+. When you tried using xcode 11.3.1 you did use the sudo xcode-select -s command to switch your default xcode installation?

**Comment by Kyle-Reis** [comment]
Hey @jupasources, we have a potential fix for this issue in code review now.

**Comment by jupasources** [comment]
@gastaffo, I think I have used the command only once when I installed version 10.x.  Haven't used it after upgrade to 11.3.1

@Kyle-Reis, good news! Waiting for fix .

**Comment by jupasources** [comment]
Hey @Kyle-Reis, any updates when the fix will be released?

**Comment by Kyle-Reis** [comment]
Hey @jupasources, current ETA is May 20.

**Comment by ShruthiAchutha** [comment]
[12.4.1](https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/releases/tag/12.4.1) release has the fix.
