### ISSUE TITLE
Problems installing wrapped iOS-App

### ISSUE THREAD

**Issue by Sn4t5** [msintuneappsdk/intune-app-wrapping-tool-ios#38]
Hello,
I am currently trying to wrap a third party app. This works without errors, but unfortunately the app can then no longer be installed on an iPhone. When I try to install this app on an iPhone I get the following error message: 
`default 10: 09: 11.432845 + 0100 mobile_installation_proxy 0x16f6b3000 handle_install: Installation failed: Error Domain = MIInstallerErrorDomain Code = 13" Failed to verify code signature of / private / var / installd / Library / Caches / com.apple.mobile.installd.staging / temp.cqDAx1 / extracted / Payload / 3rdpartyapp.iOS.app: 0xe8008016 (The executable was signed with invalid entitlements.) "UserInfo = {LibMISErrorNumber = -402620394, LegacyErrorString = ApplicationVerificationFailed, SourceFileLine = 183, FunctionName = + [MICodeSigningVerifier _validateSignatureAndCopyInfoForURL: withOptions: error:], NSLocalizedDescription = Failed to verify code signature of /private/var/installd/LibraryleCaging/install. temp.cqDAx1 / extracted / Payload / 3rdpartyapp.iOS.app: 0xe8008016 (The executable was signed with invalid entitlements.)}`
I have tried several bug fixes and adjusted the capabilities of the app identifier within the Apple Developers Program and the privisioning profile. I coordinated the capabilities with the third party, so that the same ones are also used for wrapping. I have now noticed that during the wrapping entries for InTune are made with the key chain access group. Has anyone encountered this error, or am I approaching the error incorrectly?

BR

**Comment by gastaffo** [comment]
Hi, sorry for the slow response. Are you still seeing this issue?

**Comment by Kyle-Reis** [comment]
Hey @Sn4t5, checking in again before closing out this issue. Do you still need help here?

**Comment by Kyle-Reis** [comment]
Closing out this issue due to inactivity. Please reopen if you're still having issues here!
