### ISSUE TITLE
Wrapped App crashing at startup

### ISSUE THREAD

**Issue by harikrishnagit** [msintuneappsdk/intune-app-wrapping-tool-ios#39]
We have a react-native app ejected and built on iOS using xcode. This app is then wrapped using Intune App Wrap tool (version 12.3.1) and deployed through Intune or Microsoft Endpoint manager.

When we start the app, it tries for network connection and crashes. 

**To Reproduce**
Run the app, it displays "checking your organization's data access requirements for this app" and crashes immediately 

**Expected behavior:**

**Screenshots and logs:**
error	13:03:48.208636-0400	duetexpertd	ATXGlobalAppScoresUtil: invalid normalized score
error	13:03:48.248497-0400	mobiletimerd	Connection to server via com.apple.MobileTimer.alarmserver mach port was invalidated. Removing server side connection
error	13:03:48.249572-0400	duetexpertd	<MTXPCConnectionProvider:0x102bece70 com.apple.MobileTimer.alarmserver> connection invalidated
error	13:03:48.249842-0400	duetexpertd	<MTXPCConnectionProvider:0x102bece70 com.apple.MobileTimer.alarmserver> not retrying invalidated connection
error	13:03:48.737993-0400	kernel	Sandbox: bluetoothd(75) deny(1) mach-lookup com.apple.server.bluetooth
error	13:03:50.992952-0400	kernel	Sandbox: Automated Contra(600) deny(1) sysctl-read kern.bootargs
error	13:03:50.993002-0400	kernel	Sandbox: Automated Contra(600) deny(2) file-test-existence /private/etc/.mdns_debug
error	13:03:51.414936-0400	Automated Contractor Estimator	nehelper sent invalid result code [1] for Wi-Fi information request
error	13:03:51.414988-0400	Automated Contractor Estimator	nehelper sent invalid result code [1] for Wi-Fi information request
error	13:03:51.706661-0400	Automated Contractor Estimator	BUG IN CLIENT OF libsqlite3.dylib: database integrity compromised by API violation: vnode unlinked while in use: /private/var/mobile/Containers/Data/Application/8D379D04-5BA1-4609-8FB3-7FF650527F32/Documents/SQLite/ace5.sqlite
error	13:03:51.707134-0400	Automated Contractor Estimator	nehelper sent invalid result code [1] for Wi-Fi information request
error	13:03:51.707189-0400	Automated Contractor Estimator	invalidated open fd: 7 (0x11)
error	13:03:51.707822-0400	Automated Contractor Estimator	nehelper sent invalid result code [1] for Wi-Fi information request
error	13:03:58.041280-0400	SpringBoard	[DistantDiscoverySession] ERROR: Failed to fetch hosted routing XPC endpoint. Will not retry since routing discovery session went away. (null)
error	13:03:58.043086-0400	wifid	Control Center launched
error	13:03:58.043195-0400	wifid	-[WFBlacklistEngine getBlacklistedNetworkCount] count:0
error	13:03:58.126326-0400	syncdefaultsd	Connection Invalid for service com.apple.apsd
error	13:03:59.729295-0400	kernel	Sandbox: bluetoothd(75) deny(1) mach-lookup com.apple.server.bluetooth
error	13:04:31.303879-0400	Automated Contractor Estimator	tcp_input [C1.1:3] flags=[R] seq=563751657, ack=0, win=0 state=LAST_ACK rcv_nxt=563751658, snd_una=2325025032
error	13:04:31.304239-0400	Automated Contractor Estimator	tcp_input [C1.1:3] flags=[R] seq=563751657, ack=0, win=0 state=LAST_ACK rcv_nxt=563751658, snd_una=2325025032
error	13:04:31.304506-0400	Automated Contractor Estimator	tcp_input [C1.1:3] flags=[R] seq=563751658, ack=0, win=0 state=LAST_ACK rcv_nxt=563751658, snd_una=2325025032
error	13:04:31.305126-0400	Automated Contractor Estimator	tcp_input [C1.1:3] flags=[R] seq=563751658, ack=0, win=0 state=CLOSED rcv_nxt=563751658, snd_una=2325025032

**Smartphone (please complete the following information):**
 - Device: iPad  6th gen
 - OS: iOS 13.3.1

**Intune app wrapping tool (please complete the following information):**
- Intune Wrapper 12.3.1
- ReactNative on iOS
- Yes and runds without error or crashing
- Yes, and then crashes right away

- Do you see a trend with it only being reproduced on a specific device?
Everytime

**Additional context:**

**Comment by Kyle-Reis** [comment]
Hey @harikrishnagit, could you share crash logs?

**Comment by Kyle-Reis** [comment]
Hey @harikrishnagit, are you still experiencing this issue?

**Comment by harikrishnagit** [comment]
No, we are not

    On Friday, June 26, 2020, 5:33:36 PM EDT, Kyle Reis <notifications@github.com> wrote:  
 
 


Hey @harikrishnagit, are you still experiencing this issue?

**Comment by Kyle-Reis** [comment]
Great! Please feel free to reach out if you have any other issues.

**Comment by mariot** [comment]
How did you solve this? I have the same problem.
Thanks!

**Comment by harikrishnagit** [comment]
We used a new certificate manager to issue managed certs to the devices. Configured vpn to use these certs. That fixed the issue.

**Comment by mariot** [comment]
Cool. Thanks a lot

**Comment by mariot** [comment]
What is the certificate that was missing? MDM Managed Associated Domains?
So the certificate was added to Intune or added to the user's phone?
Thanks!

**Comment by harikrishnagit** [comment]
It was the trusted root certificate. We added SCEP and used it to generate certs 

Hari. 
.
