### ISSUE TITLE
application(using xamarin forms) not open after wrapping ios ipa file after using intune wrapping tools

### ISSUE THREAD

**Issue by viveknegi51288** [msintuneappsdk/intune-app-wrapping-tool-ios#40]
**Describe the bug:**
Without wrapping app, ios file is working fine. But after wrapping app the ipa file , once click on the app it open and suddenly closed.

**To Reproduce**
1. Wrap ios build
2. Shared from appcenter to the user.
3. Click on app its closed suddenly.

**Expected behavior:**
It should open and give some error atleast.

**Screenshots and logs:**
-
- If your app is crashing post-wrapping, do you have app logs for the crash itself? - I dont have as i cannot debug the app after wrapping ipa.
- Before wrapping ipa working fine.

**Smartphone (please complete the following information):**
 - Device: [e.g. iphone 9]
 - OS: [e.g. iOS13.1]

**Intune app wrapping tool (please complete the following information):**
- What version of the wrapper are you using? Are you using the latest version? - **12.3.1**
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? Xamarin forms
- For pre-wrapping errors, does the app build without being wrapped? - Yes its working fine before wrapping.
- For post-wrapping errors, does the app launch without being wrapped? - Application closed once click on icon.
- Who is the customer? - Internal company employee. 
- Do you see a trend with it only being reproduced on a specific device? - application getting closed in every iphone.

**Additional context:**
Please share what exaclty configuration need before wrapping in plist and entitlement.

**Comment by Kyle-Reis** [comment]
Hey @viveknegi51288, could you share crash logs?

**Comment by Kyle-Reis** [comment]
Hey @viveknegi51288, checking in to see if you're still seeing this issue.

**Comment by Kyle-Reis** [comment]
Closing out this issue due to inactivity. Please reopen if you are still experiencing issues!
