### ISSUE TITLE
Missing in documentation

### ISSUE THREAD

**Issue by Dzysta** [msintuneappsdk/intune-app-wrapping-tool-ios#42]
Documents says that he application needs to have appropriate entitlements in order to be wrapped but there is no link or document what exactly it should be

**Comment by Kyle-Reis** [comment]
Hi @Dzysta, entitlements are specific to an app’s capabilities. The app developer should know what entitlements are required for their app.

**Comment by Dzysta** [comment]
Below you can find the error which i get when i'm trying to wrap the app

Warning: WARNING: This application supports opening one or more file types, but **does not have the appropriate entitlements to be supported with Intune APP.** An additional provisioning profile needs to be specified using the -x command line argument. This profile must have a wildcard application-identifier or must have an application-identifier of 'appname' and must contain at least one application group which is shared with the main application. If this profile is not specified, other Intune APP enabled applications will not be able to send files to this application.

**Comment by Kyle-Reis** [comment]
Hey @Dzysta, this is the one exception. If the wrapping tool detects that the app supports opening files sent from other apps, It attempts to inject an additional extension into to the app which can handle incoming managed data. This new extension must be signed, using the entitlements specified in the warning.

Note: We recently found an issue with this extension which may prevent the app for installing successfully on your device after being wrapped. We have a fix for this in review now.

**Comment by Kyle-Reis** [comment]
@Dzysta, the issue I referenced above should be addressed with our [latest release](https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/releases/latest) (12.6.1)
