### ISSUE TITLE
Wrapped iOS app refreshes AAD when switching back from Company Portal authentication

### ISSUE THREAD

**Issue by jacobwarduk** [msintuneappsdk/intune-app-wrapping-tool-ios#47]
We have developed a Cordova-based app which we have subsequently wrapped using the app wrapping tool for iOS.

On opening the app, we are presented with the expected AAD authentication and follow these steps: 

1. Enter email address and submit
1. Enter password and submit
1. Prompted for PIN
1. Switch to different app to get PIN
1. Come back to wrapped app

Actual: 
1. Page refreshes and prompted to enter email address (i.e. start from the beginning)

Expected: 
1. Screen to enter PIN should be displayed to enter PIN

**Comment by Kyle-Reis** [comment]
Hi @jacobwarduk, is the PIN referenced in the reproduction steps something that is sent to the user' via email or text for multi-factor auth with AAD?

**Comment by jacobwarduk** [comment]
It is from authentication app for MFA with AAD.

**Comment by Kyle-Reis** [comment]
@jacobwarduk, thanks. This sounds like an issue with the version of ADAL used by the app wrapping tool. I'll investigate if upgrading to the latest release will address it.

**Comment by jacobwarduk** [comment]
@Kyle-Reis was there any update on the above?

**Comment by Kyle-Reis** [comment]
Hey @jacobwarduk, which version of the app wrapper was the app wrapped with? I just set up MFA on my test account and after being prompted to enter authentication code and switching to a different app, then coming back, the prompt for the authentication code is still there.

**Comment by jacobwarduk** [comment]
We are using version 13.0.0

I will upgrade to 14.0.0 and see if this helps.

**Comment by Kyle-Reis** [comment]
Hey @jacobwarduk, checking in to see if you're still having this issue.

**Comment by Kyle-Reis** [comment]
Closing out this issue due to inactivity. Please reopen if you're still experiencing this issue.
