### ISSUE TITLE
Error Domain=IntuneAppPackager Code=1 "/usr/bin/defaults exited with an error

### ISSUE THREAD

**Issue by kiranprakash912** [msintuneappsdk/intune-app-wrapping-tool-ios#49]
I am trying to wrap my ipa and getting this following error
Warning: Unable to verify system settings for certificate revocation checks. If you would like to enforce certificate revocation checks, run the following commands - 'defaults write com.apple.security.revocation CRLStyle BestAttempt' and 'defaults write com.apple.security.revocation OCSPStyle BestAttempt'

Execution of defaults failed with error: Error Domain=IntuneAppPackager Code=1 "/usr/bin/defaults exited with an error." UserInfo={NSLocalizedDescription=/usr/bin/defaults exited with an error.}.

Packager Version: 14.0.0, Packager Build: 2011.9, App Build: 1.1.0, Concatenated Build: 2026.10.0

The app's Frameworks directory could not be signed. This may be because it contains files whose format was unrecognized, invalid, or unsuitable.

Cause of the error to be provided for investigation:Error Domain=IntuneAppPackager Code=1 "/usr/bin/codesign exited with an error." UserInfo={Error Description=SignFrameworksError, NSLocalizedDescription=/usr/bin/codesign exited with an error.}

**Comment by Kyle-Reis** [comment]
Hi @kiranprakash912, when wrapping the application, are you providing the certificate SHA-1 certificate hash or the certificate name?

To address the warning about certificate revocation checks, you should run the commands specified in the warning message:
defaults write com.apple.security.revocation CRLStyle BestAttempt
defaults write com.apple.security.revocation OCSPStyle BestAttempt

**Comment by Kyle-Reis** [comment]
Hi @kiranprakash912, checking in to see if you're still having this issue.

**Comment by Kyle-Reis** [comment]
Closing out this issue due to inactivity. If you're still experiencing this issue, please reopen.

**Comment by srv-distribution** [comment]
Hi, 
We are currently facing this same issue. 
We'are trying to wrap an .ipa file and we get this same error when we run the command remotely trough ssh.
When we run it locacly in a terminal it works fine. 
In addition if, in the same terminal, we reload the user profile with "su -" the command fails with the same error.

The error is: 

```
No se pudo firmar el directorio de Frameworks de la aplicación. Esto puede deberse a que contiene archivos cuyo formato no se reconoce, no es válido o no es adecuado.
La causa del error se proporciona para su investigación.:Error Domain=IntuneAppPackager Code=1 "/usr/bin/codesign finalizó con un error." UserInfo={Error Description=SignFrameworksError, NSLocalizedDescription=/usr/bin/codesign finalizó con un error.}
```

and we are using the Packager Version: 14.1.3
