### ISSUE TITLE
wrapped iOS app stuck at white screen after authentication from broker app (Microsoft Authenticator)

### ISSUE THREAD

**Issue by neerajhr19** [msintuneappsdk/intune-app-wrapping-tool-ios#53]
Hi Team,
I have an iOS app which i wrapped using intune-app-wrapping-tool-ios. 
The application was wrapped successfully and then the app was deployed using intune via Line of business app.
After deployment, the application auto installed in my device. On opening the app it says "checking your organisation data", post which it redirects to Microsoft authenticator app. 
After successful authentication at the authenticator app, it redirects back to my application and is stuck at white screen.

Please help solving this issue.

**Comment by Kyle-Reis** [comment]
Hi @neerajhr19, which version of the wrapping tool are you using to wrap? Are you providing custom AAD settings when wrapping?

**Comment by neerajhr19** [comment]
Hi @Kyle-Reis, 
I am using 14.1.3 version to wrap. 
I am also using custom AAD Settings as below 
-aa "https://login.microsoftonline.com/<my-tenant-id>"
-ac "<application/clientid>"
-ar "msauth.<app_package_name>://auth"

**Comment by Kyle-Reis** [comment]
Thanks @neerajhr19 - from the above it sounds like the app is already linking to MSAL prior to being wrapped? Could you share the version of MSAL?

**Comment by Kyle-Reis** [comment]
@neerajhr19 - Checking in to see if you're still experiencing this issue?

**Comment by Kyle-Reis** [comment]
Closing out this issue due to inactivity. Please reopen if you are still experiencing this problem.
