### ISSUE TITLE
Getting errror "The work or school account you specified doesnt have access to this app" , we have wrapped inhouse ios  app and applied app protection policy,

### ISSUE THREAD

**Issue by mdkubaib89** [msintuneappsdk/intune-app-wrapping-tool-ios#55]

**Comment by Kyle-Reis** [comment]
Hi @mdkubaib89 - this error can occur if the device is enrolled with a different account from the one you are attempting to sign in with or the app was previously enrolled with a different account on this device without being unenrolled. When the app first prompts for credentials, is the user auto-populated and are you attempting to change to a different user?

**Comment by Kyle-Reis** [comment]
@mdkubaib89 - Checking in to see if you're still having this issue?

**Comment by Kyle-Reis** [comment]
Closing out this issue due to inactivity. Please reopen if you are still experiencing this problem.
