### ISSUE TITLE
Force a IOS device to download the latest application from Intune MAM

### ISSUE THREAD

**Issue by almohammad** [msintuneappsdk/intune-app-wrapping-tool-ios#58]
Hi @Kyle-Reis 
Is there any way to force a IOS device to download the latest application using Microsoft Intune MAM?
Do I need to include the new version in the command for wrapping so user can get the latest version?

Thanks,

**Comment by Kyle-Reis** [comment]
Hi @almohammad. IT administrators can configure Intune app protection policy to block users from accessing corporate data if they attempt to use a an app version which is lower than a specified minimum. Admins can also use MAM app config to configure the URL which the user should be directed to when they receive the blocking prompt.

![image](https://user-images.githubusercontent.com/7443106/114050637-7279de00-985a-11eb-821c-792f41cd2b2c.png)

You can read more about them min app version policy here:
https://docs.microsoft.com/mem/intune/apps/app-protection-policy-settings-ios#conditional-launch

**Comment by Kyle-Reis** [comment]
To answer your question about wrapping newer versions, yes, to continue supporting Intune MAM, newer versions of the app should also be wrapped before being deployed as an update.

**Comment by Kyle-Reis** [comment]
Note: It is also recommended that you stay current with the latest version of the Intune app wrapping tool.

**Comment by Kyle-Reis** [comment]
Closing out this issue as the question has been answered. Please reach out again if you have any other questions!
