### ISSUE TITLE
Not able to wrap application with in-house provisioning profile, but able to wrap with development provisioning profile. On multiple releases, including the latest release.

### ISSUE THREAD

**Issue by virtualsb** [msintuneappsdk/intune-app-wrapping-tool-ios#59]
**Describe the bug:**
Not able to wrap application with in-house provisioning profile, but able to wrap with development provisioning profile. On multiple releases, including the latest release.

**To Reproduce**
Execute wrapping command with the latest version and tried with other releases up until 12.2.0 

The app's Frameworks directory could not be signed. This may be because it contains files whose format was unrecognized, invalid, or unsuitable.
Cause of the error to be provided for investigation:Error Domain=IntuneAppPackager Code=1 "/usr/bin/codesign exited with an error." UserInfo={Error Description=SignFrameworksError, NSLocalizedDescription=/usr/bin/codesign exited with an error.}
**Expected behavior:**

The application being wrapped with no error.

**Screenshots and logs:**

![Screenshot 2021-04-09 at 7 23 21 PM](https://user-images.githubusercontent.com/53297475/114173177-5022b600-9969-11eb-8a1e-8f23786e048c.png)
[IntuneAppPackager_log_2021_04_99_19_22_45.txt](https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/files/6285362/IntuneAppPackager_log_2021_04_99_19_22_45.txt)

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A

**Intune app wrapping tool (please complete the following information):**
- What version of the wrapper are you using? Are you using the latest version?
   I have tried : 14.3.5, 14.3.0, 14.1.3, 14.1.2, 14.1.0, 13.0.0, 12.8.0, 12.7.0, 12.2.0

- What platform is your app based in (Java, Xamarin based, Cordova, etc)?
   Cordova

- For pre-wrapping errors, does the app build without being wrapped?
  Yes
- For post-wrapping errors, does the app launch without being wrapped?
- Who is the customer?
  In house
- Do you see a trend with it only being reproduced on a specific device?

**Additional context:**
Environment Detail:
Intunes Wrapping Tool Version: 14.3.5
Version of MACOSX is 11.2.3
Version of XCode installed is Xcode 12.4

**Comment by Kyle-Reis** [comment]
Hey @virtualsb, have you tried launching the "Keychain Access" app on the mac where you are attempting to wrap the app and checking if the certificate you are using is still valid (has not expired)?

**Comment by virtualsb** [comment]
Hi @Kyle-Reis  
Thank you for your reply.
Ive checked, its still not expired, Pic below for reference
![image](https://user-images.githubusercontent.com/53297475/114195019-a94b1380-9982-11eb-904f-beca509bb9c0.jpeg)

**Comment by Kyle-Reis** [comment]
Thanks @virtualsb. For the certificate parameter (-c) provided to the app wrapping tool, it looks like you may be providing the certificate name? Are there other certificates in the keychain with the same name? If so, could you try using the SHA-1 fingerprint hash of the specific cert you want to use? Or, if other certs with the same name are expired or no longer needed, try removing them from the keychain?

**Comment by Kyle-Reis** [comment]
Ah never mind, it does look like a SHA-1 hash is being used.

**Comment by virtualsb** [comment]
@Kyle-Reis im removing other certs listed here and will retry again

**Comment by virtualsb** [comment]
> Thanks @virtualsb. For the certificate parameter (-c) provided to the app wrapping tool, it looks like you may be providing the certificate name? Are there other certificates in the keychain with the same name? If so, could you try using the SHA-1 fingerprint hash of the specific cert you want to use? Or, if other certs with the same name are expired or no longer needed, try removing them from the keychain?

It worked!
Thank you so much @Kyle-Reis Thank you!
I removed every cert that I see in the 'Keychain Access', recreate my provisioning profile, and it successfully packaged. OMG thank you so much once again

**Comment by Kyle-Reis** [comment]
Great! Reach out again if you have any questions or issues.
