### ISSUE TITLE
wrapped app is not working in ios

### ISSUE THREAD

**Issue by Abhijith-G** [msintuneappsdk/intune-app-wrapping-tool-ios#6]
Could anyone help me on this. 

![issue_ios_wrapping](https://user-images.githubusercontent.com/28953577/34674063-822a2668-f4aa-11e7-9f2b-4b4a6ecd4705.PNG)

**Comment by msintuneappsdk** [comment]
Hi @Abhijith-G, please ensure that Intune application protection policy is targeted to a group that contains the organizational account that you wish to use with the app.

**Comment by Abhijith-G** [comment]
@msintuneappsdk ,
We have wrapped another app with same methods and deployed to same group users , That works without any issue. Could you please help.

**Comment by Abhijith-G** [comment]
@msintuneappsdk Thanks for the help . The issue is resolved now. I have another question, Could you please answer me. 
After wrapping an ipa, its bundle identifier got changed. is this an expected behaviour.

![image](https://user-images.githubusercontent.com/28953577/34717337-b5afb8c8-f558-11e7-9639-aaa79b678482.png)
