### ISSUE TITLE
Conditional Access doesn't detect Intune protection policy.

### ISSUE THREAD

**Issue by rrmiraz** [msintuneappsdk/intune-app-wrapping-tool-ios#64]
When trying to log in an app with Wrapped with this tool + MSAL into an Azure tenant with a Conditional Access policy requiring an app protection policy for all cloud apps, I get an error saying " Application needs to enforce Intune protection policies" When the app has been registered in the Microsoft Endpoint, a protection policy applied to it and It is correctly loaded into the app.

Is this tool compatible with CA? What might be the problem?

**Comment by abasore** [comment]
@rrmiraz App Protection CA support does require changes to user sign-in flow for an app and therefore is not supported by the Intune App Wrapper tool. You can see all the supported/not supported features between the App Wrapper vs SDK [here](https://docs.microsoft.com/en-us/mem/intune/developer/apps-prepare-mobile-application-management#feature-comparison). 

I'll close this issue for now.
