### ISSUE TITLE
App Stuck in loading Organization Data

### ISSUE THREAD

**Issue by iit2008047** [msintuneappsdk/intune-app-wrapping-tool-ios#69]
**Describe the bug:**
App Stuck in loading Organization Data  is attached video.

**To Reproduce**
https://user-images.githubusercontent.com/76396/142638385-d59f6975-9ddf-41e1-9d3a-34218437a285.mp4

**Expected behavior:**
Organization Data is loaded and app is launched

**Comment by iit2008047** [comment]
[IntuneMAMDiagnosticFiles (6).txt](https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/files/7603298/IntuneMAMDiagnosticFiles.6.txt)

Diagnostic file for the above issue

**Comment by iit2008047** [comment]
@gastaffo this is the second issue in the same app .. would reply appreciate your help

**Comment by gastaffo** [comment]
Closing as solved in https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/issues/68
