### ISSUE TITLE
Wrapping tool wipes out localized Settings.bundle strings

### ISSUE THREAD

**Issue by rliljest** [msintuneappsdk/intune-app-wrapping-tool-ios#7]
If your application has a Settings.bundle with localized strings (Root.plist and en.lproj/Root.strings), the wrapping tool will effectively remove the en.lproj/Root.strings file. It appears to be replacing the en.lproj dir in the Settings.bundle with a different one that has en.lproj/IntuneMAMChildPaneSettings.strings.

The wrapping tool should be able to keep the en.lproj/Root.strings file in the Settings.bundle

**Comment by msintuneappsdk** [comment]
Hi @rliljest, what version of the wrapper are you using? Are you working with a native iOS application? Is this behavior not seen when the app is not wrapped?

**Comment by Kyle-Reis** [comment]
Hey @rliljest, we were able to reproduce this, and we're working on a fix.

**Comment by Kyle-Reis** [comment]
This issue is fixed in the latest release (8.0.14)

**Comment by msintuneappsdk** [comment]
Closing issue.
