### ISSUE TITLE
Wrapped iOS app stuck first time

### ISSUE THREAD

**Issue by mprabhu33** [msintuneappsdk/intune-app-wrapping-tool-ios#70]
**Describe the bug:**
Wrapped iOS app stuck first time after checking organization data requirements. If close and reopen the app, then is working fine without any issue. 

Note: Without intune iOS app wrapping, iOS app is working fine.

**To Reproduce**
1. Wrap the iOS app using intune iOS app wrapping tool.
2. Distribute the iOS app through intune MDM.
3. Open the installed app on IOS device.
4. App stuck in  the splash screen page.
5. Close the app
6. Reopen the app.
7. App is working without any issues.

Issue: App stuck for first time

Note: Without intune iOS app wrapping, iOS app is working fine.

**Expected behavior:**
First time app should work without any issue. 

**Screenshots and logs:**
Please find the attached video in the ppt. 
No logs when wrap the iOS app

**Smartphone (please complete the following information):**
 - Device: All iPhone versions. Tested on iPhoneX, iPhone11, IPhone 12
 - OS: 13.0 and 14.0
 - XCode:12.5

**Intune app wrapping tool (please complete the following information):**
- What version of the wrapper are you using? Are you using the latest version? - Version 14.7.4
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? - Flutter

[Intune IOS app issue.pptx](https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/files/7600157/Intune.IOS.app.issue.pptx)

Please let me know, how to resolve this issue?

**Comment by iit2008047** [comment]
+1

**Comment by gastaffo** [comment]
@mprabhu33 Sorry for the slow response its been a bit busy. We are currently investigating the wrapper issues and we will update this thread as soon as we have more information.

**Comment by mprabhu33** [comment]
@gastaffo Could you please update on this issue? 
Also, please find the device logs below,
Download URL: https://drive.google.com/file/d/1lWDKhc8byZE06pCPgJPtNWqW9vZDgrC3/view?usp=sharing
AppID: com.symphonysummitai.servicemanagement

**Comment by gastaffo** [comment]
@mprabhu33 Sorry for the slow response. Would you be willing to try wrapping with the `-finishLaunching` command line argument? We have noticed some apps can hang if that argument is not present.

**Comment by OmarHassan25** [comment]
> @mprabhu33 Sorry for the slow response. Would you be willing to try wrapping with the `-finishLaunching` command line argument? We have noticed some apps can hang if that argument is not present.

@mprabhu33  Could you please confirm if using this argument `-finishLaunching`  fixed the issue?

**Comment by mprabhu33** [comment]
Thanks @gastaffo. Tried iOS app wrapping with the -finishLaunching command line argument.
Wrapped iOS app working fine now.
