### ISSUE TITLE
Wrapped Xamarin Forms iOS app is stuck at initial screen

### ISSUE THREAD

**Issue by IliyanPopov** [msintuneappsdk/intune-app-wrapping-tool-ios#71]
**Describe the bug:**
Wrapped Xamarin Forms iOS app is stuck at initial screen. Popup with message "Error. Unexpected failure. Contact your IT administrator help."

**To Reproduce**
1. Start the application
2. Issue is observed 

**Expected behavior:**
Application should be usable.

**Screenshots and logs:**
![IMG_0104](https://user-images.githubusercontent.com/13572259/145176787-ed269088-b7dc-4cc2-8e0b-5dbd41a4476e.PNG)
[IntuneAppPackager_log_2021_12_342_09_53_37.txt](https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/files/7674623/IntuneAppPackager_log_2021_12_342_09_53_37.txt)

**Smartphone**
 - Device: iPAD mini 5
 - OS: iOS 15.1

**Intune app wrapping tool**
Packager Version: 15.1.4, Packager Build: 20211119.21, App Build: 9.12.99, Concatenated Build: 20211143.34.103
MACOSX v11.6
Xcode v13.1
Microsoft.Identity.Client v4.39.0
Xamarin.Forms v5.0.0.2244

**Additional context:**
MSAL is used as Authentication library. Microsoft Mobile Application Management permissions are given and granted in azure tenant.

**Comment by ShruthiAchutha** [comment]
Closing stale issues. Please reopen if you still need help with this.
