### ISSUE TITLE
Does not find XCode-Version 5 or higher

### ISSUE THREAD

**Issue by Heimo001** [msintuneappsdk/intune-app-wrapping-tool-ios#74]
**Describe the bug:**
I can not wrap my app, the tool throws an error, see the provided logs below.
Sorry for the german log file.

The tool worked a few weeks ago.
We have updated the provisioning profiles , distribution and the developer certificates.

I checked the XCode path with "xcode-select -p"
"/Applications/Xcode.app/Contents/Developer"

**To Reproduce**
1. Build the app
2. wrapp app with intune wrapping tool (params: -i -o -p -c -v)

**Expected behavior:**
Should create a wrapped app

**Screenshots and logs:**
Verbose: MACOSX-Version: 12.0.1

Verbose: Installierte Version von XCode: objc[5355]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x21204f130) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x103dd42c8). One of the two will be used. Which one is undefined.
objc[5355]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x21204f180) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x103dd4318). One of the two will be used. Which one is undefined.
Xcode 13.2.1
Build version 13C100

Error: Erforderliche Komponente fehlt.
Fehlerursache zur Untersuchung angeben:Error Domain=IntuneAppPackager Code=22 "Zum Ausführen dieses Tools ist XCode-Version 5 oder höher erforderlich." UserInfo={NSLocalizedDescription=Zum Ausführen dieses Tools ist XCode-Version 5 oder höher erforderlich.}

**Intune app wrapping tool (please complete the following information):**
- Intune app wrapping tool 15.3.0
- MacOS 12.2 (Mac Mini M1)
- Xcode 13.2.1
- Ionic/Cordova

- For pre-wrapping errors, does the app build without being wrapped?
Builds without errors, worked a few weeks ago

- For post-wrapping errors, does the app launch without being wrapped?
App launches and runs without any issues

- Do you see a trend with it only being reproduced on a specific device?

**Additional context:**

**Comment by Heimo001** [comment]
Maybe there is a relation to this issue regarding Xcode 13.2.1 and Homebrew:
https://discussions.apple.com/thread/253533981?answerId=256620966022

I will test this tomorrow by going back to Xcode 13.1.

**Comment by Heimo001** [comment]
Going back to Xcode 13.1 worked for me.

You can switch between Xcode versions: [https://stackoverflow.com/a/14756127](https://stackoverflow.com/a/14756127)

**Comment by abasore** [comment]
@Heimo001 thanks for reporting. This can happen if no XCode version is selected with 'xcode-select -s <path to xcode app>' For example, if the xcode app was deleted. The error messaging could be clearer here, so we will get that updated in a future version.

**Comment by abasore** [comment]
I'll close this issue for now.
