### ISSUE TITLE
Okta push MFA not working after using app wrapper

### ISSUE THREAD

**Issue by gv-sothebys-tristan** [msintuneappsdk/intune-app-wrapping-tool-ios#79]
**Describe the bug:**
My app uses Okta with MFA (Okta Verify) to authenticate user within the app, but after using the app wrapper Okta Verify Push has stopped working, that is it does not register that the MFA push has been accepted. Any ideas what might be the cause?

**Expected behavior:**
Okta push MFA should be registered as accepted and user should be authenticated within the app.

**Screenshots and logs:**
- If applicable, add screenshots to help explain your problem. 
<img width="388" alt="image" src="https://user-images.githubusercontent.com/89389552/168812350-09662172-9aa1-4ece-89d6-d7dde84aa81a.png">

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 15.4.1

**Intune app wrapping tool (please complete the following information):**
- What version of the wrapper are you using? Are you using the latest version? 15.4.0 (latest)
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? React Native

**Comment by vigavadi** [comment]
Hey @gv-sothebys-tristan, it seems you are using your own authentication method. You can refer to this article for more details: [App initiated authentication](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#special-considerations-when-using-msal-for-app-initiated-authentication)
Could you try setting SafariViewControllerBlockedOverride to true in the IntuneMAMSettings dictionary in your Info.plist file?
Here's the article for specifying arguments in the Info.plist file for app wrapper: [Input arguments](https://docs.microsoft.com/en-us/mem/intune/developer/app-wrapper-prepare-ios#use-a-plist-to-input-arguments)

**Comment by gv-sothebys-tristan** [comment]
> arguments

thanks will try it out!

**Comment by vigavadi** [comment]
Hey @gv-sothebys-tristan, You can send me the logs and videos at vigavadi@microsoft.com

**Comment by gv-sothebys-tristan** [comment]
> Hey @gv-sothebys-tristan, You can send me the logs and videos at [vigavadi@microsoft.com](mailto:vigavadi@microsoft.com)

Great! I have sent you a email (from:tristan.frantz.consultant@sothebys.com) 👍

**Comment by vigavadi** [comment]
@gv-sothebys-tristan Thanks for the logs. Unfortunately, Okta is not supported with MSAL which is what the app wrapper uses for authentication.

**Comment by vigavadi** [comment]
Closing this since Okta is not supported with MSAL.
