### ISSUE TITLE
Face ID Crash

### ISSUE THREAD

**Issue by ryandegruyter** [msintuneappsdk/intune-app-wrapping-tool-ios#8]
When Face ID is set on the user device, the wrapped application crashes.

Do we have to set a specific permission?

**Comment by msintuneappsdk** [comment]
Hi Ryan - 

Upon first glance, our dev team believes that you may need to try adding the [NSFaceIDUsageDescription](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW75) key to the info.plist of your app's source. This is so iOS can let show the user how the app intends to use Face ID, which is associated with one of our Intune app protection policy settings. 

If this still does not work, please send us an email to msintuneappsdk@microsoft.com with the following information so we can investigate further:

1. What is the version of the wrapper you are using? Are you using the latest version? 
2. Is there a crash error that you are getting? Do you have logs for the crash itself?
3. Are you working with a native iOS app or is it based in something else like Cordova?
4. Does the app launch without being wrapped with Intune?
5. Are you able to attach the wrapped IPA and unwrapped IPA file?

**Comment by ryandegruyter** [comment]
Correct. 

We are building a Cordova application.

Adding 

`<config-file parent="NSFaceIDUsageDescription" target="*-Info.plist">
            <string>
            </string>
        </config-file>`

In the config.xml, between the <platform name="ios"> tag resolves the issue.
