### ISSUE TITLE
Wrapped application crashes since 16.0.0 version

### ISSUE THREAD

**Issue by apinston** [msintuneappsdk/intune-app-wrapping-tool-ios#81]
**Describe the bug:**
Since the version 16.0.0 of the tool, my wrapped application crashed when I launch it.

**To Reproduce**
1. Install the wrapped application
2. Open the app
3. Login with MSAL SDK and apply policies
4. I can navigate in the application
5. Kill the app
6. Open the app
7. It crashes at launch

**Expected behavior:**
The application doesn't crash at launch

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: [e.g. iOS8.1] 15.5

**Intune app wrapping tool (please complete the following information):**
- What version of the wrapper are you using? Are you using the latest version? 16.0.5
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? React Native
- For post-wrapping errors, does the app launch without being wrapped? We don"t have the crash when the app is not wrapped
- Who is the customer? Users of my company. Application is deployed trough Intune.
- Do you see a trend with it only being reproduced on a specific device? We reproduce the crash for all our users

**Additional context:**
If we use the wrapping tool with the version 15.4.0, the application doesn't crash.
We have the crash with the versions 16.0.0, 16.0.2, 16.0.3 and 16.0.4

Thanks

**Comment by chadseippel** [comment]
Hi @apinston, could you share crash logs?

**Comment by apinston** [comment]
Hello @chadseippel,
Please find enclosed the crash logs: [wrapped-16.0.5.zip](https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/files/9148125/wrapped-16.0.5.zip)

Do you have another release that is coming soon?

Thanks,

**Comment by vigavadi** [comment]
@apinston Can you try out v16.0.8 and see if that fixes the issue.

**Comment by apinston** [comment]
Hello @vigavadi,
We still have the crash with v16.0.8.
Here the logs: [16.0.8.crash.zip](https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/files/9179200/16.0.8.crash.zip)
Thanks

**Comment by apinston** [comment]
Hello @vigavadi,
Any updates on the crash?
Thanks

**Comment by apinston** [comment]
Hello @vigavadi,
I did a new test with the version 16.0.9 and I still have the crash.
Do you know if a new release is coming?
Thanks,

**Comment by vigavadi** [comment]
@apinston Are you still seeing this issue? We made a bunch of fixes since that version. Please use one of these

- 16.1.1 if you are on Xcode13
- 17.0.0 if you are using Xcode14

**Comment by apinston** [comment]
Hello @vigavadi,
We have implemented InTune SDK on the app.
We do not use anymore the wrapping tool.
Thanks,
