### ISSUE TITLE
[iOS] Guardsquare protected builds

### ISSUE THREAD

**Issue by AlexandruSpotMe** [msintuneappsdk/intune-app-wrapping-tool-ios#84]
**Describe the bug:**
We are using Guardsquare to protect our builds, and would like then to wrap with Intune. One of the protections from Guardsquare seems to be causing a problem with Intune, namely code integrity : obj-c protection. 

```
protects against swizzling by converting Objective-C methods invocations into regular C function calls which can not be similarly swizzled.
```

If we disable this protection it seems to work well. Is there a way to still have this protection enabled while wrapping with Intune?

**To Reproduce**
Steps to reproduce the behaviour :
1. Build the app
2. Protect with iXguard
3. Wrap with Intune

**Expected behavior:**
App does not crash

**Smartphone (please complete the following information):**
 - iPhone X, iOS 15
 - iPhone 13, iOS 16

**Intune app wrapping tool (please complete the following information):**
Latest version

**Additional context:**
Does the Intune wrapping use swizzling ? If so could we maybe have a list of all the swizzled methods names we could add to our exception list ? 
Have you encountered this use case before and have any recommendations ? 

Regards,
Alexandru

**Comment by Kyle-Reis** [comment]
Hi @AlexandruSpotMe, due to the nature of how the Intune MAM SDK works, this protection cannot be enabled.

**Comment by AlexandruSpotMe** [comment]
Thank you 👍
