### ISSUE TITLE
unable to download Microsoft Intune App Wrapping Tool for iOS

### ISSUE THREAD

**Issue by FabrizioEnd** [msintuneappsdk/intune-app-wrapping-tool-ios#86]
unable to download Microsoft Intune App Wrapping Tool for iOS (IntuneAppUtil )

**Comment by Kyle-Reis** [comment]
Hi @FabrizioEnd - Could you describe the exact steps you are following to attempt to download the app wrapping tool? You should be able to download the latest release here: https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/releases/latest

**Comment by rbanker** [comment]
I will add to this: as part of our CI-CD process download the latest wrapping tool DMG from: 

https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/raw/master/Microsoft%20Intune%20Application%20Restrictions%20Packager%20for%20iOS.dmg

This has worked for years and worked up until yesterday (10/24/2022).  The link now generates a 404.  Has it moved to a new URL?

Thanks!

**Comment by Kyle-Reis** [comment]
Hi @rbanker - Could you use this URL instead: https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/raw/main/Microsoft%20Intune%20Application%20Restrictions%20Packager%20for%20iOS.dmg

We've just renamed the default branch in this repository to "main", as part of a broader effort to use more inclusive terminology in our team's private and public source repositories.

**Comment by rbanker** [comment]
The new URL worked.  Thank you @Kyle-Reis!
