### ISSUE TITLE
Intune packages crashes when tries to wrap an ipa

### ISSUE THREAD

**Issue by mugheesEdwards** [msintuneappsdk/intune-app-wrapping-tool-ios#88]
I'm using Xcode 14 and intune 17.1.
When I try to wrap my application the intune package crashes
[IntuneAppPackager_log_2022_11_321_12_19_39.txt](https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/files/10031249/IntuneAppPackager_log_2022_11_321_12_19_39.txt)

<img width="849" alt="Screenshot 2022-11-17 at 17 00 06" src="https://user-images.githubusercontent.com/118359722/202441353-eed9570f-4b84-45f6-aebb-c38c5ff36dbb.png">

All my other apps are wrapping perfectly fine with the same version but when I try to wrap this particular ipa it crashes.
Please note that this app is currently using by active users we just want to deploy it to intune portal after wrapping.

**Comment by mugheesEdwards** [comment]
Hi
I'm un
[intune 17.1.zip](https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/files/10031689/intune.17.1.zip)
able to send you an email on the given email id.
It says "Your message wasn't delivered because the recipient's email provider rejected it."
Also, I've attached the whole folder here which I am using. InfoPlist.strings are almost empty for every language.
Thanks.

**Comment by neiljac1** [comment]
Hi @mugheesEdwards. Were you trying to send a .zip file to my email or the .ipa? If an .ipa, please try renaming it to a .zip file. The .zip file you attached here is the packager, I would need to look at the application's InfoPlist.strings files to determine what is causing the crash.

Thanks,
Neil
