### ISSUE TITLE
Cannot upload a wrapped IPA to the App store

### ISSUE THREAD

**Issue by martinlingstuyl** [msintuneappsdk/intune-app-wrapping-tool-ios#9]
Hi,

What I'm trying to do is deploying a version of our (Cordova) store app to the App Store under a different name (<appname> for Intune). 

What I did was:
1. build a separate version of our existing store app with a different bundle identifier. 
2. archived it using Xcode.
3. exported the archive to IPA (focused on the app store)
4. successfully wrapped the app by running the Intune App Wrapping tool
5. Tried the IPA using application Loader. (After creating an app for it on itunesconnect)

The following error occurs when uploading the ipa.
```
1 package(s) were not uploaded because they had problems:
	/var/folders/wx/tp5h25p108q9l5rxhkwd1w_40000gn/T/46A8A416-E76B-43EF-BEB4-803CE61EE7E2/1407168145.itmsp - Error Messages:
		ERROR ITMS-90668: "Invalid Bundle Executable. The executable file '<appname> for Intune.app/Frameworks/ADAL.framework/ADAL' contains incomplete bitcode. To compile binaries with complete bitcode, open Xcode and choose Archive in the Product menu."
```

The original exported ipa does upload to the store succesfully though. The error only occurs on a wrapped ipa.

I hope someone can shed light on this.

It concerns a Cordova app, with ms-adal plugin (https://github.com/AzureAD/azure-activedirectory-library-for-cordova) used for logging in through AAD.

**Comment by martinlingstuyl** [comment]
By the way: I reproduced the error with a Blank Cordova app without any plugins. 
The issue was exactly the same. It appears the wrapping tool itself adds the ADAL framework.

**Comment by Kyle-Reis** [comment]
@martinlingstuyl, the error you are seeing related to incomplete bitcode in ADAL should be addressed in the latest release (8.1.1)

**Comment by martinlingstuyl** [comment]
Hi @Kyle-Reis,

I just tried the following:

1. Built and archived a new version of our app
2. Exported it from Xcode to ipa using Ad Hoc targeted export
3. Sideloaded the ipa using iTunes: it works
4. Downloaded the 8.1.1 version of the app wrapping tool
5. Wrapped the ad hoc app
6. Sideloaded the wrapped ipa using iTunes: it works

7. Exported it from Xcode to ipa using App Store targeted export
8. Wrapped the ipa
9. Upload the wrapped ipa using Application Launcher

Unfortunately on step 9 I get the same error as above.

**Comment by Kyle-Reis** [comment]
Hey @martinlingstuyl, does your app have bitcode enabled?

**Comment by martinlingstuyl** [comment]
No, it doesn’t.

**Comment by EbinXav** [comment]
we also facing this same issue, our app developed by Xamarin forms and wrapped using intune wrapping tool after take ipa try to put on app store error will occur

ERROR ITMS-90668: "Invalid Bundle Executable. The executable file 'UandUST.iOS.app/Frameworks/ADAL.framework/ADAL' contains incomplete bitcode. To compile binaries with complete bitcode, open Xcode and choose Archive in the Product menu."

only wrapped ipa have this problem, normal one successfully uploaded to app store.
Please give me a solution

**Comment by msintuneappsdk** [comment]
@EbinXav If you are using Xamarin to build your apps, we recommend using the Intune Xamarin Bindings for integration with Intune. Here is some documentation: https://docs.microsoft.com/en-us/intune/app-sdk-xamarin 

@martinlingstuyl We are still looking into the bitcode issue overall.

**Comment by EbinXav** [comment]
Thank you for your response

Thanks and Regards,
Ebin Xavier

**Comment by EbinXav** [comment]
Currently i'm working on this Intune SDK integration, our app using ADAL authentication for the sign in process, i got android build successfully with mam policies, but in iOS have some issues, like required some permissions on azure console. So i'm try to solve that issues.

**Comment by JaronLin** [comment]
It looks I encountered the same issue. Any update for this thread? BTW, as my experience, it also failed after uploading this app, wrapped or non-wrapped, to Intune as a LOB app and assign to specific groups. The error message shows on devices is some kind of "cannot download".

**Comment by Kyle-Reis** [comment]
@martinlingstuyl, @JaronLin, @EbinXav, just checking in to see if any of you are still blocked here before closing out this issue.

**Comment by martinlingstuyl** [comment]
We dropped Cordova and migrated to Xamarin-with-a-webview...

**Comment by Kyle-Reis** [comment]
Closing out this issue.
