### ISSUE TITLE
Error Domain=IntuneAppPackager Code=1 "/usr/bin/codesign이(가) 오류로 인해 종료되었습니다." UserInfo={Error Description=SignFrameworksError, NSLocalizedDescription=/usr/bin/codesign이(가) 오류로 인해 종료되었습니다.}

### ISSUE THREAD

**Issue by hyesun9901** [msintuneappsdk/intune-app-wrapping-tool-ios#91]
I confirmed as success that this script worked on my macbook pro.
wrapping tool version: 17.1.1

The command is ....
"/Volumes/IntuneMAMAppPackager/IntuneMAMPackager/Contents/MacOS/IntuneMAMPackager -i "$iOS_OUTPUT_PATH"/MobileDRM.ipa -o "$iOS_OUTPUT_PATH"/MobileDRM_${SITE}_${VERSION}_"20`date +%y%m%d`"_intune.ipa -p "$SHELL_PATH"/softcamp/DSMobile_Softcamp_dis_cert.mobileprovision -x \<array\>\<string\>"$SHELL_PATH"/softcamp/MobileDRM_for_Intune.mobileprovision\</string\>\</array\> -c "3E 66 2E EB 6E 1A 89 A5 75 C6 39 60 1F F8 2E A7 02 C3 A4 8C" -v true -e"

It is always success!!

![image](https://user-images.githubusercontent.com/60701949/205862407-835db8a6-af56-4955-9de2-c9ea8c76722c.png)

but, I failed when running script through the MS Azure pipeline 
Agent is Mac mini device.

Error is...
조사를 위해 제공할 오류의 원인:**Error Domain=IntuneAppPackager Code=1** "/usr/bin/codesign이(가) 오류로 인해 종료되었습니다." UserInfo={Error Description=SignFrameworksError, NSLocalizedDescription=/usr/bin/codesign이(가) 오류로 인해 종료되었습니다.}

How can I do?

[Succes_MacBookPro_IntuneAppPackager_log.txt](https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/files/10164361/Succes_MacBookPro_IntuneAppPackager_log.txt)

[Fail_on_MacMini_IntuneCommand_with_bashScript.txt](https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/files/10164367/Fail_on_MacMini_IntuneCommand_with_bashScript.txt)

**Comment by Kyle-Reis** [comment]
Glad to hear you got it working! Feel free to reach out again if you have any more issues.
