### ISSUE TITLE
Intune app wrapped successful whith wrapping tool 17.2.0 but app crash

### ISSUE THREAD

**Issue by kawarien** [msintuneappsdk/intune-app-wrapping-tool-ios#92]
**Describe the bug:**
I have MacOS Ventura 13.0.1 and xcode 14, so I used Intune wrapping tool version 17.2.0 and the wrapping is successful done.

if i try to open the app, it crash

Any help please ? thanks. 

**To Reproduce**
I am try to launch App and it crash.

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: IOS 16.2

**Intune app wrapping tool (please complete the following information):**
- What version of the wrapper are you using? 17.2.0
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? Cordova 
- For pre-wrapping errors, does the app build without being wrapped? yes
- For post-wrapping errors, does the app launch without being wrapped? yes

**Comment by neiljac1** [comment]
Hi @kawarien. Can you post the crash logs (.ips file)?

Thanks,
Neil

**Comment by kawarien** [comment]
Hi @neiljac1.  here is the crash logs
[crash log.txt](https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/files/10380682/crash.log.txt)

**Comment by neiljac1** [comment]
Hi @kawarien. Thanks for the crash log. Does your application use MSAL itself? If so, what version does it use? Also, is there anything written to the console log when the app crashes?

Thanks,
Neil

**Comment by kawarien** [comment]
Hello @neiljac1 thanks for your help.

My app use cordova-plugin-msal 2.4.2,  and there is nothing in the console.

ps : with wrapping-tool version 15.2.1 it works, my app does not crash. 

Thanks.

**Comment by neiljac1** [comment]
Hi @kawarien. What version of MSAL does the cordova-plugin-msal 2.4.2 plugin use?

Thanks,
Neil

**Comment by kawarien** [comment]
Hi @neiljac1. sorry for the late message. i was in holidays. 

I used the wrapping tool 17.2.4 , it works fine. thank you for your help.
