### ISSUE TITLE
Regression in Error Handling / User Identity Troubleshooting

### ISSUE THREAD

**Issue by ianbby** [msintuneappsdk/intune-app-wrapping-tool-ios#94]
Hey team! It looks like there's a regression in the handling of errors in the Intune wrapper. With the latest versions (I'm unfortunately not sure exactly which version regressed), error messages on launch are not showing any user identity information or allowing for removal of the account:

![no-info-or-actions](https://user-images.githubusercontent.com/77275484/225027420-e7f4f666-9329-4a6c-8cf1-b44bb3f11949.png)

This error is not troubleshootable for organizations. We cannot tell what user account / domain is trying to be used, nor can we easily assist the user in removing said account if appropriate.

Previously, starting in version 14.6.0, this messaging had been adjusted to this:
![app-useful-info-action](https://user-images.githubusercontent.com/77275484/225029127-253f44a3-a2cb-476d-b33c-08097c46baef.png)
This error message provides both the context (which user account) and a relevant action (removing the account), which allowed for speedy troubleshooting and issue resolving. The vast, vast majority of errors like this one are from users who have e.g. recently started at a new company or work with multiple companies such that they have an old or more than one Microsoft work identity on device.

**Comment by Kyle-Reis** [comment]
Hi @ianbby - Could you double check the older version of the wrapper that might have displayed the message with user info and "Remove Account" option? I'm trying to determine why this change may have been made, but I don't see any strings corresponding to the message above when syncing to our 14.6.0 release source

**Comment by ianbby** [comment]
Hi @Kyle-Reis , sure, I am confident in 14.6.0 being the moment that introduced the improved behavior. I have some old emails stemming from MS support case 25360061 that specifically reference 14.6.0 as being the version that shipped the fix. It looks like the release notes here reference the change as well - https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/releases/tag/14.6.0

**Comment by Kyle-Reis** [comment]
Hi @ianbby - I tracked down the code change which corresponds to the release note you referenced, and it appears that the message which was added differs a bit from the screenshot you shared, but the prompt displayed to the user effectively does the same thing, offering an option to remove the account. Thus far in my testing, it appears that the message which was introduced with that change is still displayed to users in cases when the user is not targeted with policies. Could you reproduce the issue and [send Intune diagnostic logs](https://learn.microsoft.com/mem/intune/developer/app-wrapper-prepare-ios#collecting-logs-for-your-wrapped-applications-from-the-device) for the app? That should help track down exactly what is leading to the different UI being displayed here. There should now be an option to upload the logs directly to Microsoft. Please select that option and wait for confirmation that the logs were successfully uploaded, then share the reference ID here with me. Thanks!

**Comment by Kyle-Reis** [comment]
Closing out this issue due to inactivity. Please reopen if you are still experiencing an issue here.
