### ISSUE TITLE
Wrapping Tool blocks Intune Conditional Access Check Policy

### ISSUE THREAD

**Issue by loet** [msintuneappsdk/intune-app-wrapping-tool-ios#96]
**Describe the bug:**
When our App is wrapped with the Intune App Wrapping Tool, the Authentication is blocked, because the Conditional Access Check Policy fails. The device stopps being recognized as managed and compliant device.
Interesting: Without wrapping the App, the Authentication and the Conditional Access Check are successful. The device is correctly recognized as managed and compliant device.

**Expected behavior:**
Like without the Wrapping tool: Successful authentication and conditional access check

**Screenshots and logs:**
- Log message on Azure: "Access has been blocked by Conditional Access policies. The access policy does not allow token issuance."

**Smartphone (please complete the following information):**
 - Device: iPad Pro
 - OS: iPadOS 16.4.1

**Intune app wrapping tool (please complete the following information):**
- What version of the wrapper are you using? Are you using the latest version? Yes, 17.4.1
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? Ionic/Capacitor
- For pre-wrapping errors, does the app build without being wrapped? Yes, and the Conditional Access Check is successful
- For post-wrapping errors, does the app launch without being wrapped? Yes
- Who is the customer? Our Company
- Do you see a trend with it only being reproduced on a specific device? No

**Comment by loet** [comment]
Just a hint to consider: Brokered Authentication might have to be supported!

See https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Leveraging-brokers-on-Android-and-iOS

**Comment by ShruthiAchutha** [comment]
Closing stale issues. Please reopen if you still need help with this.
