### ISSUE TITLE
Application AAD SSO error when wrapped

### ISSUE THREAD

**Issue by bsmith05** [msintuneappsdk/intune-app-wrapping-tool-ios#97]
**Describe the bug:**
Mobile Application using AAD authentication receives "Sorry, but we're having trouble signing you in. The required field 'request' is missing from the credential. Ensure that you have all the necessary parameters for the logon request."

The unwrapped mobile application AAD SSO auth works without issue.  In this case, I want to point out that there isn't an issue with the actual AAD federation. Basically, the authentication works as expected.

The same mobile app wrapped with 17.4.2 receives the message above when completing the same sign-in action in the application.

**Expected behavior:**
The mobile application SSO should behave the same wrapped and unwrapped.  The wrapped application should not throw an error described above.

**Smartphone (please complete the following information):**
iPadOS 16.x.x

**Intune app wrapping tool (please complete the following information):**
- What version of the wrapper are you using? Are you using the latest version? -latest
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? - Objective-C, C++, and Swift
- For pre-wrapping errors, does the app build without being wrapped? - None
- For post-wrapping errors, does the app launch without being wrapped? - None
- Who is the customer? -NA
- Do you see a trend with it only being reproduced on a specific device? - No, multiple devices.

**Additional context:**
This app originally had the MSAL library baked into the app.  When wrapped, the app would crash instantly (incident reported a few months ago).  The developer removed the MSAL library and then re-wrapped the app.  At this time the app would launch but now has the SSO error described above.  The unwrapped app without the MSAL library worked without issue.  The wrapped app has the reported issue (above).

I'm thinking that something in the app isn't picking up some code in the MSAL library injected during wrapping.

**Comment by neiljac1** [comment]
Hi @bsmith05,

Can you please send the Intune log files to neiljac@microsoft.com?

Thank you,
Neil

**Comment by ShruthiAchutha** [comment]
Closing inactive issue.
