### ISSUE TITLE
Can we wrap an Maui app with this Intune wrapping tool

### ISSUE THREAD

**Issue by MikeP0911** [msintuneappsdk/intune-app-wrapping-tool-ios#98]
Hi 

Just curious if we can use this to wrap the app created with Maui.

Thanks in advance

**Comment by gastaffo** [comment]
Hi there,
I am not familiar with MAUI but if it produces an iOS app IPA or bundle then the app wrapper should be able to wrap and inject the SDK. Note that with the app wrapper you must have policy assigned to access the app and the wrapper will force a sign in at first launch.
